/**
 * Cross-language conformance for the logical lane substrate.
 *
 * Every vector here comes from `fixtures/remote-transport/`, which
 * `crates/cockpit-proto/tests/remote_transport_fixtures.rs` generates from the
 * Rust codecs. No byte literal is duplicated between the two languages: if
 * either side changes, the shared file stops matching and both suites fail.
 */
import { describe, expect, it } from "vitest";
import bulkFixture from "../fixtures/remote-transport/bulk.json" with { type: "json" };
import channelsFixture from "../fixtures/remote-transport/channels.json" with { type: "json" };
import classificationFixture from "../fixtures/remote-transport/classification.json" with {
  type: "json",
};
import constantsFixture from "../fixtures/remote-transport/constants.json" with { type: "json" };
import fragmentsFixture from "../fixtures/remote-transport/fragments.json" with { type: "json" };
import framesFixture from "../fixtures/remote-transport/frames.json" with { type: "json" };
import { bulkTransferRefSchema, clientEnvelopeSchema, PROTOCOL_VERSION } from ".";
import {
  BULK_ABORT_BYTES,
  BULK_BEGIN_BYTES_WITH_OPTIONS,
  BULK_BEGIN_BYTES_WITHOUT_OPTIONS,
  BULK_CHUNK_ENVELOPE_BYTES,
  BULK_COMPLETE_BYTES,
  bytesToHex,
  CONTROL_STREAM_ID,
  carrierTransmitsWatermark,
  classifyTag,
  decodeCarrierRecord,
  decodeRemoteBulkMessage,
  decodeRemoteCarrierFragment,
  decodeRemoteTransportFrame,
  encodeCarrierRecord,
  encodeRemoteBulkMessage,
  encodeRemoteCarrierFragment,
  encodeRemoteTransportFrame,
  FRAGMENT_FLAG_END,
  FRAME_FLAG_END_STREAM,
  FRAME_FLAG_RESET_STREAM,
  FRAME_FLAGS_DEFINED,
  fragmentFrame,
  frameIdFromText,
  hexToBytes,
  LANE_FRAGMENT_TOTAL_BYTES,
  laneForChannelId,
  laneForChannelLabel,
  laneFromId,
  MAX_BULK_CHUNK_PAYLOAD_BYTES,
  MAX_COMPLETED_FRAME_MEMORY,
  MAX_FRAGMENT_COUNT,
  MAX_LOGICAL_PAYLOAD_BYTES,
  MAX_SERIALIZED_FRAME_BYTES,
  REASSEMBLY_DEADLINE_MS,
  REMOTE_BULK_MIME_CLASS_CODES,
  REMOTE_BULK_MIME_CLASS_MAX_TOTAL_LENGTH,
  REMOTE_CARRIER_FRAGMENT_HEADER_BYTES,
  REMOTE_CARRIER_FRAGMENT_MAX_PAYLOAD_BYTES,
  REMOTE_LANE_CHANNELS,
  REMOTE_LANE_IDS,
  REMOTE_LANE_MAX_PAYLOAD_BYTES,
  REMOTE_LANES,
  REMOTE_MESSAGE_CLASS_LANES,
  REMOTE_TRANSPORT_FRAME_HEADER_BYTES,
  type RemoteBulkMimeClass,
  type RemoteCarrierFragmentV1,
  RemoteFragmentReassembler,
  type RemoteLane,
  type RemoteMessageClass,
  type RemoteMessageKind,
  RemoteStreamSequences,
  RemoteTransportError,
  type RemoteTransportFrameV1,
  sha256,
  U64_MAX_VALUE,
  UNKNOWN_MESSAGE_TAG,
  validateStreamId,
} from "./remote-transport-lanes";

/**
 * Fixture rows, typed explicitly.
 *
 * The JSON files are generated by Rust, so their inferred types carry optional
 * members (large vectors omit `encodedHex`). Normalising through these
 * interfaces keeps the assertions readable and the access checked.
 */
interface PayloadSpec {
  readonly fill: number;
  readonly length: number;
}

interface FrameCaseRow {
  readonly name: string;
  readonly lane: string;
  readonly laneId: number;
  readonly flags: number;
  readonly streamId: string;
  readonly streamSeq: string;
  readonly frameId: string;
  readonly payload: PayloadSpec;
  readonly payloadDigestHex: string;
  readonly headerHex: string;
  readonly serializedLength: number;
  readonly encodedHex?: string;
}

interface FragmentRow {
  readonly index: number;
  readonly count: number;
  readonly flags: number;
  readonly payloadLength: number;
  readonly encodedLength: number;
  readonly headerHex: string;
  readonly encodedHex?: string;
}

interface FragmentCaseRow {
  readonly name: string;
  readonly lane: string;
  readonly streamId: string;
  readonly frameId: string;
  readonly payload: PayloadSpec;
  readonly serializedFrameLength: number;
  readonly fragmentCount: number;
  readonly fragments: readonly FragmentRow[];
}

interface BulkCaseRow {
  readonly name: string;
  readonly encodedHex: string;
  readonly encodedLength: number;
}

interface ClassificationRow {
  readonly tag: string;
  readonly class: string;
  readonly lane: string;
  readonly inlinePayloadBound: string;
}

const frameCases: readonly FrameCaseRow[] = framesFixture.cases;
const fragmentCases: readonly FragmentCaseRow[] = fragmentsFixture.cases;
const bulkCases: readonly BulkCaseRow[] = bulkFixture.cases;
const classificationMessages: Readonly<Record<RemoteMessageKind, readonly ClassificationRow[]>> = {
  request: classificationFixture.messages.request,
  response: classificationFixture.messages.response,
  event: classificationFixture.messages.event,
};

/** Rebuild a fixture payload described generatively. */
function buildPayload(spec: PayloadSpec): Uint8Array {
  return new Uint8Array(spec.length).fill(spec.fill);
}

function asLane(value: string): RemoteLane {
  const lane = REMOTE_LANES.find((candidate) => candidate === value);
  if (lane === undefined) throw new Error(`unknown lane in fixture: ${value}`);
  return lane;
}

/** The reason code of a thrown transport error. */
function reasonOf(run: () => unknown): string {
  try {
    run();
  } catch (error) {
    if (error instanceof RemoteTransportError) return error.reason;
    throw error;
  }
  throw new Error("expected a RemoteTransportError");
}

async function asyncReasonOf(run: () => Promise<unknown>): Promise<string> {
  try {
    await run();
  } catch (error) {
    if (error instanceof RemoteTransportError) return error.reason;
    throw error;
  }
  throw new Error("expected a RemoteTransportError");
}

describe("remote_transport_frame_cross_language_conformance", () => {
  it("agrees with Rust on every checked-in frame vector", async () => {
    expect(frameCases.length).toBeGreaterThan(0);

    for (const testCase of frameCases) {
      const lane = asLane(testCase.lane);
      const payload = buildPayload(testCase.payload);
      const encoded = await encodeRemoteTransportFrame({
        lane,
        flags: testCase.flags,
        streamId: BigInt(testCase.streamId),
        streamSeq: BigInt(testCase.streamSeq),
        frameId: frameIdFromText(testCase.frameId),
        payload,
      });

      // Byte-exact header, produced independently by each language.
      expect(bytesToHex(encoded.subarray(0, REMOTE_TRANSPORT_FRAME_HEADER_BYTES))).toBe(
        testCase.headerHex,
      );
      expect(encoded.length).toBe(testCase.serializedLength);
      expect(bytesToHex(await sha256(payload))).toBe(testCase.payloadDigestHex);
      if (testCase.encodedHex !== undefined) {
        expect(bytesToHex(encoded)).toBe(testCase.encodedHex);
      }

      const decoded = await decodeRemoteTransportFrame(encoded);
      expect(decoded.lane).toBe(lane);
      expect(decoded.flags).toBe(testCase.flags);
      expect(decoded.streamId).toBe(BigInt(testCase.streamId));
      expect(decoded.streamSeq).toBe(BigInt(testCase.streamSeq));
      expect(bytesToHex(decoded.payload)).toBe(bytesToHex(payload));
    }
  });

  it("pins the exact 72-byte layout and field widths", () => {
    const frame = constantsFixture.frame;
    expect(frame.headerBytes).toBe(72);
    expect(REMOTE_TRANSPORT_FRAME_HEADER_BYTES).toBe(frame.headerBytes);
    // 1 + 1 + 2 + 8 + 8 + 16 + 4 + 32 = 72
    expect(1 + 1 + 2 + 8 + 8 + 16 + 4 + 32).toBe(72);
    expect(frame.offsets).toEqual({
      version: 0,
      lane: 1,
      flags: 2,
      streamId: 4,
      streamSeq: 12,
      frameId: 20,
      payloadLength: 36,
      payloadDigest: 40,
      payload: 72,
    });
    expect(MAX_LOGICAL_PAYLOAD_BYTES).toBe(frame.maxLogicalPayloadBytes);
    expect(MAX_SERIALIZED_FRAME_BYTES).toBe(frame.maxSerializedFrameBytes);
    expect(frame.maxSerializedFrameBytes).toBe(524_360);
    // Lane ids and caps match the Rust table.
    for (const lane of constantsFixture.lanes) {
      const name = asLane(lane.lane);
      expect(REMOTE_LANE_IDS[name]).toBe(lane.laneId);
      expect(REMOTE_LANE_MAX_PAYLOAD_BYTES[name]).toBe(lane.maxPayloadBytes);
    }
    expect(laneFromId(3)).toBeUndefined();
  });

  it("encodes u64 fields big-endian and never as JSON numbers", async () => {
    const highValues = frameCases.find(
      (testCase) => testCase.name === "interactive_daemon_stream_high_values",
    );
    expect(highValues).toBeDefined();
    if (highValues === undefined) return;
    // JSON carries CanonicalU64DecimalStringV1, not a lossy JS number.
    expect(typeof highValues.streamId).toBe("string");
    expect(typeof highValues.streamSeq).toBe("string");
    expect(BigInt(highValues.streamId)).toBe(18446744073709551615n);

    const encoded = await encodeRemoteTransportFrame({
      lane: asLane(highValues.lane),
      flags: highValues.flags,
      streamId: BigInt(highValues.streamId),
      streamSeq: BigInt(highValues.streamSeq),
      frameId: frameIdFromText(highValues.frameId),
      payload: buildPayload(highValues.payload),
    });
    // Most significant byte first.
    expect(bytesToHex(encoded.subarray(4, 12))).toBe("ffffffffffffffff");
    expect(bytesToHex(encoded.subarray(12, 20))).toBe("0102030405060708");
  });

  it("accepts only the two defined flag bits", async () => {
    expect(FRAME_FLAGS_DEFINED).toBe(constantsFixture.frame.flags.defined);
    expect(FRAME_FLAG_END_STREAM).toBe(constantsFixture.frame.flags.endStream);
    expect(FRAME_FLAG_RESET_STREAM).toBe(constantsFixture.frame.flags.resetStream);

    const base = frameCases[0];
    expect(base).toBeDefined();
    if (base === undefined) return;
    const encoded = await encodeRemoteTransportFrame({
      lane: asLane(base.lane),
      flags: 0,
      streamId: BigInt(base.streamId),
      streamSeq: BigInt(base.streamSeq),
      frameId: frameIdFromText(base.frameId),
      payload: buildPayload(base.payload),
    });
    for (const bad of [0x0004, 0x0008, 0x0100, 0x8000, 0xffff]) {
      const corrupt = encoded.slice();
      corrupt[2] = (bad >>> 8) & 0xff;
      corrupt[3] = bad & 0xff;
      await expect(asyncReasonOf(() => decodeRemoteTransportFrame(corrupt))).resolves.toBe(
        "unknown_flag_bit",
      );
    }
  });

  it("fails strictly on every malformed frame", async () => {
    const good = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: 0,
      streamId: 2n,
      streamSeq: 0n,
      frameId: frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA"),
      payload: new Uint8Array([1, 2, 3, 4]),
    });

    await expect(
      asyncReasonOf(() => decodeRemoteTransportFrame(good.subarray(0, 71))),
    ).resolves.toBe("header_too_short");

    const wrongVersion = good.slice();
    wrongVersion[0] = 2;
    await expect(asyncReasonOf(() => decodeRemoteTransportFrame(wrongVersion))).resolves.toBe(
      "unsupported_version",
    );

    const wrongLane = good.slice();
    wrongLane[1] = 3;
    await expect(asyncReasonOf(() => decodeRemoteTransportFrame(wrongLane))).resolves.toBe(
      "unknown_lane",
    );

    const trailing = new Uint8Array(good.length + 1);
    trailing.set(good);
    await expect(asyncReasonOf(() => decodeRemoteTransportFrame(trailing))).resolves.toBe(
      "trailing_bytes",
    );

    await expect(
      asyncReasonOf(() => decodeRemoteTransportFrame(good.subarray(0, good.length - 1))),
    ).resolves.toBe("payload_length_mismatch");

    const corruptPayload = good.slice();
    const lastIndex = good.length - 1;
    corruptPayload[lastIndex] = corruptPayload[lastIndex]! ^ 0xff;
    await expect(asyncReasonOf(() => decodeRemoteTransportFrame(corruptPayload))).resolves.toBe(
      "digest_mismatch",
    );

    // A declared length beyond the lane cap fails before any allocation.
    const oversized = good.slice();
    oversized[36] = 0x00;
    oversized[37] = 0x09;
    oversized[38] = 0x27;
    oversized[39] = 0xc0;
    await expect(asyncReasonOf(() => decodeRemoteTransportFrame(oversized))).resolves.toBe(
      "payload_cap_exceeded",
    );
  });

  it("enforces per-lane payload caps", async () => {
    await expect(
      asyncReasonOf(() =>
        encodeRemoteTransportFrame({
          lane: "control",
          flags: 0,
          streamId: CONTROL_STREAM_ID,
          streamSeq: 0n,
          frameId: frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA"),
          payload: new Uint8Array(REMOTE_LANE_MAX_PAYLOAD_BYTES.control + 1),
        }),
      ),
    ).resolves.toBe("payload_cap_exceeded");
  });

  it("enforces stream parity, control-only stream 0, and sequence rules", () => {
    // Client streams are nonzero and even; daemon streams odd.
    expect(() => validateStreamId(2n, "client", "interactive")).not.toThrow();
    expect(() => validateStreamId(3n, "daemon", "interactive")).not.toThrow();
    expect(reasonOf(() => validateStreamId(2n, "daemon", "interactive"))).toBe(
      "stream_parity_violation",
    );
    expect(reasonOf(() => validateStreamId(3n, "client", "bulk"))).toBe("stream_parity_violation");
    // Stream 0 is control-only.
    expect(() => validateStreamId(0n, "client", "control")).not.toThrow();
    expect(reasonOf(() => validateStreamId(0n, "client", "interactive"))).toBe("zero_stream_id");
    expect(reasonOf(() => validateStreamId(0n, "daemon", "bulk"))).toBe("zero_stream_id");

    const sequences = new RemoteStreamSequences();
    sequences.accept("interactive", 2n, 0n);
    sequences.accept("interactive", 2n, 1n);
    expect(reasonOf(() => sequences.accept("interactive", 2n, 3n))).toBe("sequence_gap");
    expect(reasonOf(() => sequences.accept("interactive", 2n, 0n))).toBe("sequence_regression");
    // Lanes track streams independently.
    sequences.accept("bulk", 2n, 0n);
    expect(sequences.trackedStreams).toBe(2);
  });

  it("retires a closed stream id so terminal frames cannot be replayed", () => {
    const sequences = new RemoteStreamSequences("client");
    sequences.accept("interactive", 2n, 0n);
    sequences.close("interactive", 2n);
    expect(sequences.trackedStreams).toBe(0);
    // The id is retired: replaying its terminal frame, or reusing the id at
    // all, is refused rather than dispatched a second time.
    expect(reasonOf(() => sequences.accept("interactive", 2n, 0n))).toBe("stream_closed");
    // A higher, never-used id is still fine.
    sequences.accept("interactive", 4n, 0n);
    expect(sequences.trackedStreams).toBe(1);
  });

  it("survives a higher-id close while a fragmented frame is mid-reassembly", async () => {
    // The production composition: reassemble, decode, then apply stream rules.
    // Calling `accept` directly cannot reproduce this ordering, which is
    // exactly why a direct-call test could not catch the retirement bug.
    // The reassembler IS the receive gate: it validates, decodes, and applies
    // the stream rules itself, exactly as Rust does.
    const reassembler = new RemoteFragmentReassembler("client");
    const deliver = (fragment: RemoteCarrierFragmentV1) => reassembler.accept(fragment, 0);

    // Stream 4: a genuinely fragmented first frame.
    const bigId = frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA");
    const bigSerialized = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: 0,
      streamId: 4n,
      streamSeq: 0n,
      frameId: bigId,
      payload: new Uint8Array(200_000).fill(0xa5),
    });
    const bigFragments = fragmentFrame("interactive", bigId, bigSerialized);
    expect(bigFragments.length).toBeGreaterThan(1);
    for (const fragment of bigFragments.slice(0, -1)) {
      expect(await deliver(fragment)).toBeUndefined();
    }

    // Stream 6: a small terminal frame that completes and closes first.
    const smallId = frameIdFromText("AgMEBQYHCAkKCwwNDg8QEQ");
    const smallSerialized = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: FRAME_FLAG_END_STREAM,
      streamId: 6n,
      streamSeq: 0n,
      frameId: smallId,
      payload: new Uint8Array(32).fill(0x5a),
    });
    const smallFragments = fragmentFrame("interactive", smallId, smallSerialized);
    expect(smallFragments.length).toBe(1);
    expect(await deliver(smallFragments[0]!)).toBeDefined();

    // Stream 4 now finishes: it must be dispatched, not retired.
    const completed = await deliver(bigFragments[bigFragments.length - 1]!);
    expect(completed).toBeDefined();
    expect(completed?.streamId).toBe(4n);

    // Stream 6 is still genuinely retired. Proven with a frame id that was
    // never dispatched, so it cannot be in the retention memory and this
    // exercises stream retirement alone — replaying stream 6's own
    // terminal frame would instead hit frame-id retention and be idempotently
    // dropped, a separate mechanism proven by "keeps frame ids unique for the
    // retention window". Keeping them apart is deliberate: a test that passes
    // only because two mechanisms compose cannot tell you which one broke.
    const rebornId = frameIdFromText("AwQFBgcICQoLDA0ODxAREg");
    const reborn = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: 0,
      streamId: 6n,
      streamSeq: 0n,
      frameId: rebornId,
      payload: new Uint8Array(8).fill(3),
    });
    const rebornFragments = fragmentFrame("interactive", rebornId, reborn);
    expect(await asyncReasonOf(() => deliver(rebornFragments[0]!))).toBe("stream_closed");
  });

  it("retires by contiguous prefix, not by the highest closed id", () => {
    const sequences = new RemoteStreamSequences("client");
    sequences.accept("interactive", 6n, 0n);
    sequences.close("interactive", 6n);
    // Ordinal 3 is closed, but the prefix cannot pass ordinal 1 (stream 2).
    expect(sequences.pendingClosedOrdinals).toBe(1);
    expect(() => sequences.accept("interactive", 4n, 0n)).not.toThrow();
    expect(reasonOf(() => sequences.accept("interactive", 6n, 0n))).toBe("stream_closed");

    // Filling the prefix collapses the closed set back to empty.
    sequences.close("interactive", 4n);
    sequences.accept("interactive", 2n, 0n);
    sequences.close("interactive", 2n);
    expect(sequences.pendingClosedOrdinals).toBe(0);
    for (const retired of [2n, 4n, 6n]) {
      expect(reasonOf(() => sequences.accept("interactive", retired, 0n))).toBe("stream_closed");
    }
  });

  it("bounds the number of streams one peer may hold open", () => {
    const sequences = new RemoteStreamSequences("client", 4);
    for (let nth = 0n; nth < 4n; nth++) {
      sequences.accept("interactive", (nth + 1n) * 2n, 0n);
    }
    expect(sequences.trackedStreams).toBe(4);
    expect(reasonOf(() => sequences.accept("interactive", 10n, 0n))).toBe("stream_limit_exceeded");
  });

  it("bounds how far a peer may run ahead of the retired prefix", () => {
    const sequences = new RemoteStreamSequences("client", 256, 8n);
    for (let nth = 1n; nth < 8n; nth++) {
      const stream = (nth + 1n) * 2n; // never uses stream 2, stalling the prefix
      sequences.accept("interactive", stream, 0n);
      sequences.close("interactive", stream);
    }
    expect(sequences.pendingClosedOrdinals).toBeLessThanOrEqual(8);
    expect(reasonOf(() => sequences.accept("interactive", 100n, 0n))).toBe("stream_limit_exceeded");
  });

  it("rejects undefined fragment flag bits on encode", () => {
    const frameId = frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA");
    // Rust cannot construct RemoteFragmentFlags(0x0002); TS must not encode it.
    expect(
      reasonOf(() =>
        encodeRemoteCarrierFragment({
          lane: "bulk",
          flags: 0x0002,
          frameId,
          fragmentIndex: 0,
          fragmentCount: 2,
          bytes: new Uint8Array(4),
        }),
      ),
    ).toBe("unknown_flag_bit");
    for (const bad of [0x0004, 0x8000, 0xffff]) {
      expect(
        reasonOf(() =>
          encodeRemoteCarrierFragment({
            lane: "bulk",
            flags: bad,
            frameId,
            fragmentIndex: 0,
            fragmentCount: 1,
            bytes: new Uint8Array(4),
          }),
        ),
      ).toBe("unknown_flag_bit");
    }
  });

  it("range-checks u16 fragment fields Rust bounds by type", () => {
    const frameId = frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA");
    // A negative index would encode as 0xffff — an input Rust cannot build.
    expect(
      reasonOf(() =>
        encodeRemoteCarrierFragment({
          lane: "bulk",
          flags: 0,
          frameId,
          fragmentIndex: -1,
          fragmentCount: 1,
          bytes: new Uint8Array(4),
        }),
      ),
    ).toBe("integer_out_of_range");
    for (const bad of [65_536, 1.5, Number.NaN]) {
      expect(
        reasonOf(() =>
          encodeRemoteCarrierFragment({
            lane: "bulk",
            flags: 0,
            frameId,
            fragmentIndex: 0,
            fragmentCount: bad,
            bytes: new Uint8Array(4),
          }),
        ),
      ).toBe("integer_out_of_range");
    }
  });
});

describe("remote_transport_fragment_conformance", () => {
  it("agrees with Rust on every fragment vector", () => {
    expect(fragmentCases.length).toBeGreaterThan(0);

    for (const testCase of fragmentCases) {
      const lane = asLane(testCase.lane);
      const frameId = frameIdFromText(testCase.frameId);
      // Rebuild the serialized frame from its recorded header plus payload.
      const fragments = testCase.fragments;
      expect(fragments.length).toBe(testCase.fragmentCount);

      for (const [index, fragment] of fragments.entries()) {
        expect(fragment.index).toBe(index);
        expect(fragment.count).toBe(testCase.fragmentCount);
        const isFinal = index + 1 === testCase.fragmentCount;
        expect(fragment.flags).toBe(isFinal ? FRAGMENT_FLAG_END : 0);
        // The header is exactly 26 bytes.
        expect(fragment.headerHex.length).toBe(REMOTE_CARRIER_FRAGMENT_HEADER_BYTES * 2);
        expect(fragment.encodedLength).toBe(
          REMOTE_CARRIER_FRAGMENT_HEADER_BYTES + fragment.payloadLength,
        );

        // Re-encode this exact fragment and compare the header byte for byte.
        const rebuilt = encodeRemoteCarrierFragment({
          lane,
          flags: fragment.flags,
          frameId,
          fragmentIndex: fragment.index,
          fragmentCount: fragment.count,
          bytes: new Uint8Array(fragment.payloadLength),
        });
        expect(bytesToHex(rebuilt.subarray(0, REMOTE_CARRIER_FRAGMENT_HEADER_BYTES))).toBe(
          fragment.headerHex,
        );
        if (fragment.encodedHex !== undefined) {
          const decoded = decodeRemoteCarrierFragment(hexToBytes(fragment.encodedHex));
          expect(decoded.lane).toBe(lane);
          expect(decoded.fragmentIndex).toBe(fragment.index);
          expect(decoded.fragmentCount).toBe(fragment.count);
          expect(bytesToHex(decoded.frameId)).toBe(bytesToHex(frameId));
        }
      }
    }
  });

  it("closes the 65,471-byte bound exactly against the Noise carrier", () => {
    const noise = constantsFixture.noise;
    const fragment = constantsFixture.fragment;
    // 65,535 - 16 = 65,519 plaintext
    expect(noise.maxPlaintextBytes).toBe(noise.recordMaxCiphertextBytes - noise.aeadTagBytes);
    expect(noise.maxPlaintextBytes).toBe(65_519);
    // - 14 record header = 65,505
    expect(noise.recordPayloadBytes).toBe(noise.maxPlaintextBytes - noise.recordHeaderBytes);
    expect(noise.recordPayloadBytes).toBe(65_505);
    // - 8 watermark = 65,497 fragment total
    expect(fragment.laneFragmentTotalBytes).toBe(
      noise.recordPayloadBytes - noise.peerSeenThroughWatermarkBytes,
    );
    expect(fragment.laneFragmentTotalBytes).toBe(65_497);
    // - 26 fragment header = 65,471 payload
    expect(fragment.maxPayloadBytes).toBe(fragment.laneFragmentTotalBytes - fragment.headerBytes);
    expect(fragment.maxPayloadBytes).toBe(65_471);
    expect(65_519 - 14 - 8 - 26).toBe(65_471);

    expect(REMOTE_CARRIER_FRAGMENT_HEADER_BYTES).toBe(fragment.headerBytes);
    expect(REMOTE_CARRIER_FRAGMENT_MAX_PAYLOAD_BYTES).toBe(fragment.maxPayloadBytes);
    expect(LANE_FRAGMENT_TOTAL_BYTES).toBe(fragment.laneFragmentTotalBytes);
    // 1 + 1 + 2 + 16 + 2 + 2 + 2 = 26
    expect(1 + 1 + 2 + 16 + 2 + 2 + 2).toBe(26);
    expect(fragment.offsets).toEqual({
      version: 0,
      lane: 1,
      flags: 2,
      frameId: 4,
      fragmentIndex: 20,
      fragmentCount: 22,
      fragmentPayloadLength: 24,
      bytes: 26,
    });
  });

  it("splits the maximal frame into exactly nine fragments", async () => {
    expect(MAX_FRAGMENT_COUNT).toBe(constantsFixture.fragment.maxFragmentCount);
    expect(MAX_FRAGMENT_COUNT).toBe(9);
    expect(Math.ceil(524_360 / 65_471)).toBe(9);

    const maximal = fragmentCases.find(
      (testCase) => testCase.name === "nine_fragment_maximal_bulk",
    );
    expect(maximal).toBeDefined();
    if (maximal === undefined) return;
    expect(maximal.serializedFrameLength).toBe(524_360);
    expect(maximal.fragmentCount).toBe(9);

    const frameId = frameIdFromText(maximal.frameId);
    const serialized = await encodeRemoteTransportFrame({
      lane: "bulk",
      flags: 0,
      streamId: BigInt(maximal.streamId),
      streamSeq: 0n,
      frameId,
      payload: buildPayload(maximal.payload),
    });
    expect(serialized.length).toBe(maximal.serializedFrameLength);

    const fragments = fragmentFrame("bulk", frameId, serialized);
    expect(fragments.length).toBe(9);
    for (const [index, fragment] of fragments.entries()) {
      const expected = maximal.fragments[index];
      expect(expected).toBeDefined();
      if (expected === undefined) continue;
      expect(fragment.bytes.length).toBe(expected.payloadLength);
      expect(fragment.flags).toBe(expected.flags);
      const encoded = encodeRemoteCarrierFragment(fragment);
      expect(encoded.length).toBe(expected.encodedLength);
      expect(bytesToHex(encoded.subarray(0, REMOTE_CARRIER_FRAGMENT_HEADER_BYTES))).toBe(
        expected.headerHex,
      );
      // Eight full fragments at exactly the carrier budget.
      if (index < 8) {
        expect(fragment.bytes.length).toBe(65_471);
        expect(encoded.length).toBe(65_497);
      }
      expect(encoded.length).toBeLessThanOrEqual(LANE_FRAGMENT_TOTAL_BYTES);
    }
    // 8 * 65,471 = 523,768, leaving 592 bytes in the final fragment.
    expect(fragments[8]?.bytes.length).toBe(524_360 - 8 * 65_471);
    expect(fragments[8]?.bytes.length).toBe(592);

    // Reassembly rebuilds the frame and its digest validates.
    const reassembler = new RemoteFragmentReassembler("client");
    let rebuilt: RemoteTransportFrameV1 | undefined;
    for (const fragment of fragments) {
      const wire = decodeRemoteCarrierFragment(encodeRemoteCarrierFragment(fragment));
      const done = await reassembler.accept(wire, 0);
      if (done !== undefined) rebuilt = done;
    }
    expect(rebuilt).toBeDefined();
    if (rebuilt === undefined) return;
    expect(rebuilt.payload.length).toBe(maximal.payload.length);
    expect(bytesToHex(rebuilt.payload)).toBe(bytesToHex(buildPayload(maximal.payload)));
  });

  it("rejects malformed fragment shapes", () => {
    const frameId = frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA");
    const good = encodeRemoteCarrierFragment({
      lane: "interactive",
      flags: FRAGMENT_FLAG_END,
      frameId,
      fragmentIndex: 0,
      fragmentCount: 1,
      bytes: new Uint8Array([9, 9, 9]),
    });

    const zeroCount = good.slice();
    zeroCount[22] = 0;
    zeroCount[23] = 0;
    expect(reasonOf(() => decodeRemoteCarrierFragment(zeroCount))).toBe("zero_fragment_count");

    const overCount = good.slice();
    overCount[22] = 0;
    overCount[23] = 10;
    expect(reasonOf(() => decodeRemoteCarrierFragment(overCount))).toBe("fragment_count_exceeded");

    const badIndex = good.slice();
    badIndex[20] = 0;
    badIndex[21] = 5;
    badIndex[22] = 0;
    badIndex[23] = 5;
    expect(reasonOf(() => decodeRemoteCarrierFragment(badIndex))).toBe(
      "fragment_index_out_of_range",
    );

    // Only END exists at the fragment level.
    for (const bad of [0x0002, 0x0004, 0x8000]) {
      const corrupt = good.slice();
      corrupt[2] = (bad >>> 8) & 0xff;
      corrupt[3] = bad & 0xff;
      expect(reasonOf(() => decodeRemoteCarrierFragment(corrupt))).toBe("unknown_flag_bit");
    }

    // END belongs to the final fragment alone.
    expect(
      reasonOf(() =>
        encodeRemoteCarrierFragment({
          lane: "bulk",
          flags: FRAGMENT_FLAG_END,
          frameId,
          fragmentIndex: 0,
          fragmentCount: 2,
          bytes: new Uint8Array(4),
        }),
      ),
    ).toBe("fragment_end_flag_misplaced");
    expect(
      reasonOf(() =>
        encodeRemoteCarrierFragment({
          lane: "bulk",
          flags: 0,
          frameId,
          fragmentIndex: 1,
          fragmentCount: 2,
          bytes: new Uint8Array(4),
        }),
      ),
    ).toBe("fragment_end_flag_misplaced");

    const trailing = new Uint8Array(good.length + 1);
    trailing.set(good);
    expect(reasonOf(() => decodeRemoteCarrierFragment(trailing))).toBe("trailing_bytes");
    expect(reasonOf(() => decodeRemoteCarrierFragment(good.subarray(0, good.length - 1)))).toBe(
      "fragment_length_mismatch",
    );
    expect(reasonOf(() => decodeRemoteCarrierFragment(good.subarray(0, 25)))).toBe(
      "header_too_short",
    );
  });

  it("bounds reassembly to 16 frames, 8 MiB, and a 5-second deadline", async () => {
    const reassembly = constantsFixture.reassembly;
    expect(reassembly.maxIncompleteFramesPerPeer).toBe(16);
    expect(reassembly.maxBytesPerPeer).toBe(8 * 1024 * 1024);
    expect(reassembly.deadlineMs).toBe(5_000);

    const makeFragments = async (seed: number) => {
      const frameId = new Uint8Array(16).fill(seed);
      const serialized = await encodeRemoteTransportFrame({
        lane: "bulk",
        flags: 0,
        streamId: 4n,
        streamSeq: 0n,
        frameId,
        payload: new Uint8Array(150_000),
      });
      return fragmentFrame("bulk", frameId, serialized);
    };

    // Exact duplicates are idempotent; a conflicting one closes the stream.
    const reassembler = new RemoteFragmentReassembler("client");
    const first = await makeFragments(1);
    expect(await reassembler.accept(first[0]!, 0)).toBeUndefined();
    expect(await reassembler.accept(first[0]!, 0)).toBeUndefined();
    expect(reassembler.incompleteFrames).toBe(1);
    const conflicting = { ...first[0]!, bytes: first[0]!.bytes.slice() };
    conflicting.bytes[0] = conflicting.bytes[0]! ^ 0xff;
    expect(await asyncReasonOf(() => reassembler.accept(conflicting, 0))).toBe("fragment_conflict");

    // The injected deadline expires incomplete state at exactly 5 seconds.
    expect(reassembler.expire(4_999)).toBe(0);
    expect(reassembler.incompleteFrames).toBe(1);
    expect(reassembler.expire(5_000)).toBe(1);
    expect(reassembler.incompleteFrames).toBe(0);
    expect(reassembler.bufferedBytes).toBe(0);

    // The 16-frame ceiling holds.
    const bounded = new RemoteFragmentReassembler("client");
    for (let seed = 1; seed <= 16; seed++) {
      const fragments = await makeFragments(seed);
      expect(await bounded.accept(fragments[0]!, 0)).toBeUndefined();
    }
    expect(bounded.incompleteFrames).toBe(16);
    const overflow = await makeFragments(17);
    expect(await asyncReasonOf(() => bounded.accept(overflow[0]!, 0))).toBe(
      "reassembly_frame_limit",
    );
  });

  it("refuses a reassembled frame whose payload digest does not match", async () => {
    // Every fragment is individually well-formed; only the logical payload is
    // corrupt. The receive gate must reject it rather than hand the caller
    // "complete" data — that gate has to live in the reassembler, not in the
    // caller, or a real consumer would simply never perform the check.
    const frameId = frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA");
    const serialized = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: 0,
      streamId: 2n,
      streamSeq: 0n,
      frameId,
      payload: new Uint8Array(80_000).fill(0x11),
    });
    // Flip a payload byte, leaving the declared digest in the header intact.
    const corrupted = serialized.slice();
    const last = corrupted.length - 1;
    corrupted[last] = corrupted[last]! ^ 0xff;

    const fragments = fragmentFrame("interactive", frameId, corrupted);
    expect(fragments.length).toBeGreaterThan(1);
    const reassembler = new RemoteFragmentReassembler("client");
    // Each fragment decodes cleanly on its own.
    for (const fragment of fragments.slice(0, -1)) {
      const wire = decodeRemoteCarrierFragment(encodeRemoteCarrierFragment(fragment));
      expect(await reassembler.accept(wire, 0)).toBeUndefined();
    }
    const finalWire = decodeRemoteCarrierFragment(
      encodeRemoteCarrierFragment(fragments[fragments.length - 1]!),
    );
    expect(await asyncReasonOf(() => reassembler.accept(finalWire, 0))).toBe("digest_mismatch");
  });

  it("keeps frame ids unique for the retention window", async () => {
    // The same id on stream 2 seq 0 then seq 1: per-stream sequencing is
    // satisfied by both, so only frame-id retention can catch the second.
    const reassembler = new RemoteFragmentReassembler("client");
    const reused = frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA");

    const build = async (streamSeq: bigint, fill: number) => {
      const serialized = await encodeRemoteTransportFrame({
        lane: "interactive",
        flags: 0,
        streamId: 2n,
        streamSeq,
        frameId: reused,
        payload: new Uint8Array(48).fill(fill),
      });
      return fragmentFrame("interactive", reused, serialized);
    };

    const first = await build(0n, 1);
    expect(await reassembler.accept(first[0]!, 0)).toBeDefined();
    expect(reassembler.rememberedFrames).toBe(1);

    const reuse = await build(1n, 2);
    expect(await asyncReasonOf(() => reassembler.accept(reuse[0]!, 0))).toBe("fragment_conflict");

    // A byte-identical retry is permitted but non-dispatching.
    expect(await reassembler.accept(first[0]!, 0)).toBeUndefined();

    // Bounded, and drains on the same deadline as reassembly.
    expect(reassembler.rememberedFrames).toBeLessThanOrEqual(MAX_COMPLETED_FRAME_MEMORY);
    reassembler.expire(REASSEMBLY_DEADLINE_MS);
    expect(reassembler.rememberedFrames).toBe(0);
  });

  it("refuses a reassembled frame that breaks the stream rules", async () => {
    // Stream 0 is control-only; an interactive frame riding it must not be
    // dispatched even though every fragment is well-formed.
    const frameId = frameIdFromText("AgMEBQYHCAkKCwwNDg8QEQ");
    const serialized = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: 0,
      streamId: 0n,
      streamSeq: 0n,
      frameId,
      payload: new Uint8Array(16).fill(7),
    });
    const fragments = fragmentFrame("interactive", frameId, serialized);
    const reassembler = new RemoteFragmentReassembler("client");
    expect(await asyncReasonOf(() => reassembler.accept(fragments[0]!, 0))).toBe("zero_stream_id");
  });

  it("produces byte-identical fragments for WebRTC and the fallback", async () => {
    const frameId = frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA");
    const serialized = await encodeRemoteTransportFrame({
      lane: "bulk",
      flags: 0,
      streamId: 4n,
      streamSeq: 0n,
      frameId,
      payload: new Uint8Array(70_000).fill(0x5a),
    });
    const fragments = fragmentFrame("bulk", frameId, serialized);
    expect(fragments.length).toBeGreaterThan(1);

    // A nonzero watermark: if a carrier ever let it bleed into the fragment,
    // the recovered bytes would differ and this test would catch it.
    const watermark = 0x0102030405060708n;

    for (const fragment of fragments) {
      const canonical = encodeRemoteCarrierFragment(fragment);
      const webrtcRecord = encodeCarrierRecord("webrtc_data_channel", canonical, watermark);
      const fallbackRecord = encodeCarrierRecord("websocket_fallback", canonical, watermark);

      // The two carriers really are different on the wire...
      expect(fallbackRecord.length).toBe(webrtcRecord.length + 8);
      expect(fallbackRecord.length).toBe(
        webrtcRecord.length + constantsFixture.noise.peerSeenThroughWatermarkBytes,
      );
      expect(bytesToHex(fallbackRecord.subarray(0, 8))).toBe("0102030405060708");
      expect(bytesToHex(webrtcRecord)).not.toBe(bytesToHex(fallbackRecord));

      // ...yet both recover byte-identical fragment bytes, equal to the
      // canonical encoding. This is the property criterion 3 requires.
      const fromWebrtc = decodeCarrierRecord("webrtc_data_channel", webrtcRecord);
      const fromFallback = decodeCarrierRecord("websocket_fallback", fallbackRecord);
      expect(bytesToHex(fromWebrtc)).toBe(bytesToHex(canonical));
      expect(bytesToHex(fromFallback)).toBe(bytesToHex(canonical));
      expect(bytesToHex(fromWebrtc)).toBe(bytesToHex(fromFallback));

      // Both decode back to the same fragment.
      expect(decodeRemoteCarrierFragment(fromFallback)).toEqual(
        decodeRemoteCarrierFragment(fromWebrtc),
      );
      // Each record fits the shared 65,497-byte carrier budget.
      expect(canonical.length).toBeLessThanOrEqual(LANE_FRAGMENT_TOTAL_BYTES);
    }
    expect(carrierTransmitsWatermark("webrtc_data_channel")).toBe(false);
    expect(carrierTransmitsWatermark("websocket_fallback")).toBe(true);
  });
});

describe("remote_transport_fixed_channel_contract", () => {
  it("matches the Rust channel table exactly", () => {
    expect(channelsFixture.channels.length).toBe(3);
    expect(REMOTE_LANE_CHANNELS.length).toBe(channelsFixture.channels.length);

    for (const [index, expected] of channelsFixture.channels.entries()) {
      const actual = REMOTE_LANE_CHANNELS[index];
      expect(actual).toBeDefined();
      if (actual === undefined) continue;
      expect(actual.lane).toBe(expected.lane);
      expect(actual.laneId).toBe(expected.laneId);
      expect(actual.channelId).toBe(expected.channelId);
      expect(actual.label).toBe(expected.label);
      expect(actual.negotiated).toBe(expected.negotiated);
      expect(actual.ordered).toBe(expected.ordered);
      expect(actual.reliable).toBe(expected.reliable);
      expect(actual.compressed).toBe(expected.compressed);
      expect(actual.maxPayloadBytes).toBe(expected.maxPayloadBytes);
    }
  });

  it("pins ids 0/2/4, exact labels, and ordered/reliable/pre-negotiated settings", () => {
    expect(channelsFixture.channels.map((channel) => channel.channelId)).toEqual([0, 2, 4]);
    expect(channelsFixture.channels.map((channel) => channel.label)).toEqual([
      "flycockpit.control.v1",
      "flycockpit.interactive.v1",
      "flycockpit.bulk.v1",
    ]);
    for (const channel of channelsFixture.channels) {
      expect(channel.negotiated).toBe(true);
      expect(channel.ordered).toBe(true);
      expect(channel.reliable).toBe(true);
      expect(channel.compressed).toBe(false);
    }
    // Channel ids are distinct from lane ids, so the two cannot be swapped.
    expect(channelsFixture.channels.map((channel) => channel.laneId)).toEqual([0, 1, 2]);
  });

  it("admits no dynamic channel", () => {
    for (const unknown of [1, 3, 5, 6, 65_535]) {
      expect(reasonOf(() => laneForChannelId(unknown))).toBe("unknown_lane");
    }
    for (const unknown of ["flycockpit.media.v1", "flycockpit.control.v2", "control", ""]) {
      expect(reasonOf(() => laneForChannelLabel(unknown))).toBe("unknown_lane");
    }
    expect(laneForChannelId(0)).toBe("control");
    expect(laneForChannelId(2)).toBe("interactive");
    expect(laneForChannelId(4)).toBe("bulk");
  });
});

describe("remote_transport_classification_is_exhaustive", () => {
  const kinds: RemoteMessageKind[] = ["request", "response", "event"];

  it("mirrors every Rust classification row", () => {
    for (const kind of kinds) {
      const rows = classificationMessages[kind];
      expect(rows.length).toBeGreaterThan(0);
      expect(rows.length).toBe(classificationFixture.counts[kind]);

      const tags = new Set<string>();
      for (const row of rows) {
        // The lane must be exactly what the class implies: no row may carry a
        // lane the class does not own.
        const messageClass = row.class as RemoteMessageClass;
        expect(REMOTE_MESSAGE_CLASS_LANES[messageClass]).toBe(row.lane);
        expect(row.tag).not.toBe(UNKNOWN_MESSAGE_TAG);
        expect(tags.has(row.tag)).toBe(false);
        tags.add(row.tag);
      }
    }
  });

  it("agrees with Rust on the class → lane map", () => {
    expect(classificationFixture.classLanes.length).toBe(
      Object.keys(REMOTE_MESSAGE_CLASS_LANES).length,
    );
    for (const entry of classificationFixture.classLanes) {
      expect(REMOTE_MESSAGE_CLASS_LANES[entry.class as RemoteMessageClass]).toBe(entry.lane);
    }
  });

  it("fails unknown and unclassified message kinds", () => {
    const table = classificationMessages.request;
    // The sentinel itself comes from the shared fixture, not a local literal.
    expect(UNKNOWN_MESSAGE_TAG).toBe(classificationFixture.unknownMessageTag);
    expect(classifyTag(table, "attach").tag).toBe("attach");
    // The catch-all has no lane, and neither does anything invented.
    for (const invented of [UNKNOWN_MESSAGE_TAG, "definitely_not_a_variant", "", "Attach"]) {
      expect(reasonOf(() => classifyTag(table, invented))).toBe("unclassified_message");
    }
  });

  it("prevents client lane promotion", () => {
    // Only the bulk transfer class may ride the bulk lane; nothing else can
    // promote itself onto it, and the lane is never an input.
    for (const kind of kinds) {
      for (const row of classificationMessages[kind]) {
        if (row.lane === "bulk") expect(row.class).toBe("bulk_chunk");
        if (row.class === "bulk_chunk") expect(row.lane).toBe("bulk");
      }
    }
    // Control rows are structurally bounded, so a control flood cannot carry
    // an arbitrary application payload.
    for (const kind of kinds) {
      for (const row of classificationMessages[kind]) {
        if (row.lane === "control") expect(row.inlinePayloadBound).toBe("bounded");
      }
    }
  });

  it("has no unbounded inline payload anywhere", () => {
    const inventory = new Set(
      classificationFixture.oversizedInventory.map((entry) => `${entry.kind}:${entry.tag}`),
    );
    expect(inventory.size).toBeGreaterThan(0);
    const migrated = new Set<string>();
    for (const kind of kinds) {
      for (const row of classificationMessages[kind]) {
        if (row.inlinePayloadBound !== "bounded") migrated.add(`${kind}:${row.tag}`);
      }
    }
    // The >512 KiB inventory and the migrated set are the same set.
    expect([...migrated].sort()).toEqual([...inventory].sort());

    // The two structurally unbounded blob paths carry references now.
    const requests = classificationMessages.request;
    const responses = classificationMessages.response;
    expect(requests.find((row) => row.tag === "import_session_archive")?.inlinePayloadBound).toBe(
      "bulk_reference",
    );
    expect(responses.find((row) => row.tag === "export_session_data")?.inlinePayloadBound).toBe(
      "bulk_reference",
    );
    expect(requests.find((row) => row.tag === "upload_attachment_chunk")?.lane).toBe("bulk");
  });

  it("classifies terminal, file, image, and archive traffic", () => {
    const requests = classificationMessages.request;
    const events = classificationMessages.event;
    for (const tag of ["open_terminal", "terminal_input", "terminal_resize", "close_terminal"]) {
      expect(requests.find((row) => row.tag === tag)?.class).toBe("terminal_io");
    }
    for (const tag of ["terminal_output", "terminal_clipboard", "terminal_closed"]) {
      expect(events.find((row) => row.tag === tag)?.class).toBe("terminal_io");
    }
    for (const tag of ["fs_read", "fs_write", "fs_list", "fs_stat"]) {
      expect(requests.find((row) => row.tag === tag)?.lane).toBe("interactive");
    }
    // Cancelling an upload must not queue behind the upload itself.
    expect(requests.find((row) => row.tag === "cancel_attachment_upload")?.lane).toBe("control");
  });
});

describe("remote_bulk_window_and_integrity", () => {
  it("agrees with Rust on every bulk vector", () => {
    expect(bulkCases.length).toBeGreaterThan(0);
    for (const testCase of bulkCases) {
      const bytes = hexToBytes(testCase.encodedHex);
      expect(bytes.length).toBe(testCase.encodedLength);
      const message = decodeRemoteBulkMessage(bytes);
      // Re-encoding reproduces the Rust bytes exactly.
      expect(bytesToHex(encodeRemoteBulkMessage(message))).toBe(testCase.encodedHex);
    }
  });

  it("pins the exact envelope sizes", () => {
    const bulk = constantsFixture.bulk;
    expect(bulk.beginBytesWithoutOptions).toBe(1 + 16 + 1 + 1 + 8);
    expect(bulk.beginBytesWithOptions).toBe(1 + 16 + 1 + 8 + 32 + 1 + 8);
    expect(bulk.chunkEnvelopeBytes).toBe(1 + 16 + 4 + 8 + 4);
    expect(bulk.completeBytes).toBe(1 + 16 + 8 + 32);
    expect(bulk.abortBytes).toBe(1 + 16 + 1);
    expect(BULK_BEGIN_BYTES_WITHOUT_OPTIONS).toBe(bulk.beginBytesWithoutOptions);
    expect(BULK_BEGIN_BYTES_WITH_OPTIONS).toBe(bulk.beginBytesWithOptions);
    expect(BULK_CHUNK_ENVELOPE_BYTES).toBe(bulk.chunkEnvelopeBytes);
    expect(BULK_COMPLETE_BYTES).toBe(bulk.completeBytes);
    expect(BULK_ABORT_BYTES).toBe(bulk.abortBytes);
    // 524,288 - 33 = 524,255, so a maximal chunk exactly fills the lane cap.
    expect(bulk.maxChunkPayloadBytes).toBe(524_255);
    expect(MAX_BULK_CHUNK_PAYLOAD_BYTES).toBe(bulk.maxChunkPayloadBytes);
    expect(bulk.chunkEnvelopeBytes + bulk.maxChunkPayloadBytes).toBe(MAX_LOGICAL_PAYLOAD_BYTES);
    expect(bulkFixture.maximalChunk.encodedLength).toBe(MAX_LOGICAL_PAYLOAD_BYTES);
  });

  it("closes optionBits to exactly 0x00 and 0x03", () => {
    const unknown = bulkCases.find((row) => row.name === "begin_unknown_length");
    const known = bulkCases.find((row) => row.name === "begin_known_prehashed");
    expect(unknown).toBeDefined();
    expect(known).toBeDefined();
    if (unknown === undefined || known === undefined) return;

    const unknownBytes = hexToBytes(unknown.encodedHex);
    const knownBytes = hexToBytes(known.encodedHex);
    expect(unknownBytes[17]).toBe(0x00);
    expect(knownBytes[17]).toBe(0x03);

    // Unknown length: both optional fields absent, incremental hashing.
    const decodedUnknown = decodeRemoteBulkMessage(unknownBytes);
    expect(decodedUnknown.kind).toBe("begin");
    if (decodedUnknown.kind === "begin") {
      expect(decodedUnknown.totalLength).toBeUndefined();
      expect(decodedUnknown.expectedSha256).toBeUndefined();
    }
    // Known/prehashed: both present.
    const decodedKnown = decodeRemoteBulkMessage(knownBytes);
    if (decodedKnown.kind === "begin") {
      expect(decodedKnown.totalLength).toBeDefined();
      expect(decodedKnown.expectedSha256).toBeDefined();
      expect(bytesToHex(decodedKnown.expectedSha256!)).toBe(bulkFixture.payloadDigestHex);
    }

    // 0x01, 0x02 and every other spelling fail.
    for (const bad of [0x01, 0x02, 0x04, 0x07, 0x80, 0xff]) {
      const corrupt = knownBytes.slice();
      corrupt[17] = bad;
      expect(reasonOf(() => decodeRemoteBulkMessage(corrupt))).toBe("bulk_option_bits");
    }
    // Field/bit disagreement fails: 0x03 bits over a 0x00-sized body.
    const disagreeing = unknownBytes.slice();
    disagreeing[17] = 0x03;
    expect(reasonOf(() => decodeRemoteBulkMessage(disagreeing))).toBe("bulk_length_mismatch");
  });

  it("rejects unknown kinds, classes, reasons, and trailing bytes", () => {
    const abort = bulkCases.find((row) => row.name === "abort_cancelled");
    expect(abort).toBeDefined();
    if (abort === undefined) return;
    const abortBytes = hexToBytes(abort.encodedHex);

    for (const bad of [0x00, 0x05, 0xc8]) {
      const corrupt = abortBytes.slice();
      corrupt[0] = bad;
      expect(reasonOf(() => decodeRemoteBulkMessage(corrupt))).toBe("bulk_unknown_kind");
    }
    for (const bad of [0x00, 0x06, 0xff]) {
      const corrupt = abortBytes.slice();
      corrupt[17] = bad;
      expect(reasonOf(() => decodeRemoteBulkMessage(corrupt))).toBe("bulk_unknown_abort_reason");
    }
    const trailing = new Uint8Array(abortBytes.length + 1);
    trailing.set(abortBytes);
    expect(reasonOf(() => decodeRemoteBulkMessage(trailing))).toBe("trailing_bytes");
    expect(reasonOf(() => decodeRemoteBulkMessage(new Uint8Array()))).toBe("header_too_short");

    // Mime classes and abort reasons are closed sets shared with Rust.
    for (const entry of constantsFixture.bulk.mimeClasses) {
      const name = entry.name as RemoteBulkMimeClass;
      expect(typeof entry.code).toBe("number");
      expect(entry.code).toBeGreaterThan(0);
      // maxTotalLength travels as a canonical decimal string, never a number.
      expect(typeof entry.maxTotalLength).toBe("string");
      expect(BigInt(entry.maxTotalLength)).toBeLessThanOrEqual(
        BigInt(constantsFixture.bulk.maxTransferBytes),
      );
      expect(name.length).toBeGreaterThan(0);
    }
  });

  it("keeps window, transfer, and image bounds", () => {
    const bulk = constantsFixture.bulk;
    expect(BigInt(bulk.maxReceiverWindowBytes)).toBe(4n * 1024n * 1024n);
    expect(BigInt(bulk.maxTransferBytes)).toBe(512n * 1024n * 1024n);
    // The landed image limits stay authoritative.
    const image = bulk.mimeClasses.find((entry) => entry.name === "image");
    const imageSet = bulk.mimeClasses.find((entry) => entry.name === "image_set");
    expect(BigInt(image?.maxTotalLength ?? "0")).toBe(4n * 1024n * 1024n);
    expect(BigInt(imageSet?.maxTotalLength ?? "0")).toBe(8n * 1024n * 1024n);
    // maxTotalLength is the minimum of the class limit and 512 MiB.
    for (const entry of bulk.mimeClasses) {
      expect(BigInt(entry.maxTotalLength)).toBeLessThanOrEqual(BigInt(bulk.maxTransferBytes));
    }
  });

  it("enforces class limits on both encode and decode, exactly as Rust does", () => {
    const known = bulkCases.find((row) => row.name === "begin_known_prehashed");
    expect(known).toBeDefined();
    if (known === undefined) return;

    // begin layout: [0]=kind [1..17]=id [17]=optionBits [18..26]=totalLength
    //               [26..58]=sha256 [58]=mimeClass [59..67]=maxTotalLength
    const writeU64 = (target: Uint8Array, offset: number, value: bigint): void => {
      let remaining = value;
      for (let i = 7; i >= 0; i--) {
        target[offset + i] = Number(remaining & 0xffn);
        remaining >>= 8n;
      }
    };

    // A begin that claims the image class but advertises the 512 MiB global
    // ceiling. Rust returns bulk_class_limit; TypeScript must too.
    const wrongLimit = hexToBytes(known.encodedHex);
    wrongLimit[58] = REMOTE_BULK_MIME_CLASS_CODES.image;
    expect(reasonOf(() => decodeRemoteBulkMessage(wrongLimit))).toBe("bulk_class_limit");

    // A correctly-advertised image class whose declared total is one byte over
    // the 4 MiB single-image limit.
    const overClass = hexToBytes(known.encodedHex);
    overClass[58] = REMOTE_BULK_MIME_CLASS_CODES.image;
    writeU64(overClass, 59, 4n * 1024n * 1024n);
    writeU64(overClass, 18, 4n * 1024n * 1024n + 1n);
    expect(reasonOf(() => decodeRemoteBulkMessage(overClass))).toBe("bulk_transfer_limit");

    // Exactly at the limit is accepted, so the bound is not off by one.
    const atClass = hexToBytes(known.encodedHex);
    atClass[58] = REMOTE_BULK_MIME_CLASS_CODES.image;
    writeU64(atClass, 59, 4n * 1024n * 1024n);
    writeU64(atClass, 18, 4n * 1024n * 1024n);
    expect(decodeRemoteBulkMessage(atClass).kind).toBe("begin");

    // The same rule applies on encode.
    expect(
      reasonOf(() =>
        encodeRemoteBulkMessage({
          kind: "begin",
          transferId: frameIdFromText(bulkFixture.transferId),
          totalLength: 4n * 1024n * 1024n + 1n,
          expectedSha256: new Uint8Array(32),
          mimeClass: "image",
          maxTotalLength: REMOTE_BULK_MIME_CLASS_MAX_TOTAL_LENGTH.image,
        }),
      ),
    ).toBe("bulk_transfer_limit");

    // The class table agrees with the Rust-generated fixture.
    for (const entry of constantsFixture.bulk.mimeClasses) {
      const name = entry.name as RemoteBulkMimeClass;
      expect(REMOTE_BULK_MIME_CLASS_MAX_TOTAL_LENGTH[name]).toBe(BigInt(entry.maxTotalLength));
      expect(REMOTE_BULK_MIME_CLASS_CODES[name]).toBe(entry.code);
    }
  });

  it("rejects out-of-range integers instead of truncating them", async () => {
    // Rust gets this from u64; TypeScript must not silently sign-extend.
    for (const bad of [-1n, U64_MAX_VALUE + 1n]) {
      await expect(
        asyncReasonOf(() =>
          encodeRemoteTransportFrame({
            lane: "interactive",
            flags: 0,
            streamId: bad,
            streamSeq: 0n,
            frameId: frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA"),
            payload: new Uint8Array(1),
          }),
        ),
      ).resolves.toBe("integer_out_of_range");
    }
    // The maximum is representable and round-trips.
    const atMax = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: 0,
      streamId: U64_MAX_VALUE,
      streamSeq: 0n,
      frameId: frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA"),
      payload: new Uint8Array(1),
    });
    expect((await decodeRemoteTransportFrame(atMax)).streamId).toBe(U64_MAX_VALUE);
  });

  it("routes 16-byte identifiers through the landed opaque-ID validator", async () => {
    // Rust rejects an all-zero id via tag_protocol_id_bytes; so must TypeScript.
    const good = await encodeRemoteTransportFrame({
      lane: "interactive",
      flags: 0,
      streamId: 2n,
      streamSeq: 0n,
      frameId: frameIdFromText("AQIDBAUGBwgJCgsMDQ4PEA"),
      payload: new Uint8Array([1, 2, 3]),
    });
    const zeroed = good.slice();
    zeroed.fill(0, 20, 36);
    await expect(asyncReasonOf(() => decodeRemoteTransportFrame(zeroed))).resolves.toBe(
      "payload_length_mismatch",
    );

    const abort = bulkCases.find((row) => row.name === "abort_cancelled");
    expect(abort).toBeDefined();
    if (abort === undefined) return;
    const zeroTransfer = hexToBytes(abort.encodedHex);
    zeroTransfer.fill(0, 1, 17);
    expect(reasonOf(() => decodeRemoteBulkMessage(zeroTransfer))).toBe("bulk_unknown_transfer");
  });

  it("matches Rust's validation order on doubly-invalid messages", () => {
    const known = bulkCases.find((row) => row.name === "begin_known_prehashed");
    const abort = bulkCases.find((row) => row.name === "abort_cancelled");
    expect(known).toBeDefined();
    expect(abort).toBeDefined();
    if (known === undefined || abort === undefined) return;

    // BEGIN that is invalid in BOTH the transfer id and the option bits.
    // Rust reads the id first, so the id's reason must win in TypeScript too.
    const doublyBadBegin = hexToBytes(known.encodedHex);
    doublyBadBegin.fill(0, 1, 17);
    doublyBadBegin[17] = 0x02;
    expect(reasonOf(() => decodeRemoteBulkMessage(doublyBadBegin))).toBe("bulk_unknown_transfer");
    // With a valid id, the option bits are reached and reported.
    const badBitsOnly = hexToBytes(known.encodedHex);
    badBitsOnly[17] = 0x02;
    expect(reasonOf(() => decodeRemoteBulkMessage(badBitsOnly))).toBe("bulk_option_bits");

    // ABORT invalid in both the id and the reason code: id wins, as in Rust.
    const doublyBadAbort = hexToBytes(abort.encodedHex);
    doublyBadAbort.fill(0, 1, 17);
    doublyBadAbort[17] = 0xff;
    expect(reasonOf(() => decodeRemoteBulkMessage(doublyBadAbort))).toBe("bulk_unknown_transfer");
    const badReasonOnly = hexToBytes(abort.encodedHex);
    badReasonOnly[17] = 0xff;
    expect(reasonOf(() => decodeRemoteBulkMessage(badReasonOnly))).toBe(
      "bulk_unknown_abort_reason",
    );
  });

  it("refuses a chunk larger than the lane cap", () => {
    expect(
      reasonOf(() =>
        encodeRemoteBulkMessage({
          kind: "chunk",
          transferId: frameIdFromText(bulkFixture.transferId),
          chunkIndex: 0,
          offset: 0n,
          bytes: new Uint8Array(MAX_BULK_CHUNK_PAYLOAD_BYTES + 1),
        }),
      ),
    ).toBe("payload_cap_exceeded");
  });
});

describe("remote transport constants", () => {
  it("shares the settled NDJSON successor cap and lane schedule with Rust", () => {
    expect(constantsFixture.ndjsonMaxFrameBytes).toBe(1_048_576);
    expect(constantsFixture.ndjsonMaxFrameBytes).toBe(1024 * 1024);
    expect(constantsFixture.laneSchedule).toEqual([
      "control",
      "interactive",
      "control",
      "bulk",
      "interactive",
      "control",
      "interactive",
      "bulk",
    ]);
    const limits = constantsFixture.queueLimits;
    expect(limits.controlFrames).toBe(256);
    expect(limits.controlBytes).toBe(2 * 1024 * 1024);
    expect(limits.interactiveFrames).toBe(512);
    expect(limits.interactiveBytes).toBe(8 * 1024 * 1024);
    expect(limits.bulkFrames).toBe(128);
    expect(limits.bulkBytes).toBe(8 * 1024 * 1024);
    expect(limits.aggregateBytes).toBe(16 * 1024 * 1024);
    expect(limits.controlReservedBytes).toBe(1024 * 1024);
    expect(limits.controlReservedFrames).toBe(32);
    expect(limits.interactiveReservedBytes).toBe(2 * 1024 * 1024);
    expect(limits.sharedPoolBytes).toBe(
      limits.aggregateBytes - limits.controlReservedBytes - limits.interactiveReservedBytes,
    );
  });
});

describe("daemon-wire bulk schemas reject what Rust rejects", () => {
  it("validates opaque ids with the landed codec, not a regex", () => {
    const valid = {
      transfer_id: "AQIDBAUGBwgJCgsMDQ4PEA",
      total_length: "12",
      sha256: "ab".repeat(32),
      mime_class: "archive",
    };
    expect(bulkTransferRefSchema.safeParse(valid).success).toBe(true);

    // The all-zero id matches /^[A-Za-z0-9_-]{22}$/ but Rust's
    // tag_protocol_id_bytes rejects it, so the schema must too.
    expect(
      bulkTransferRefSchema.safeParse({ ...valid, transfer_id: "AAAAAAAAAAAAAAAAAAAAAA" }).success,
    ).toBe(false);
    for (const bad of [
      "AQIDBAUGBwgJCgsMDQ4PE",
      "AQIDBAUGBwgJCgsMDQ4PEA=",
      "AQIDBAUGBwgJCgsMDQ4P+A",
    ]) {
      expect(bulkTransferRefSchema.safeParse({ ...valid, transfer_id: bad }).success).toBe(false);
    }
  });

  it("bounds chunk indexes at u32, as Rust's type does", () => {
    const base = {
      v: PROTOCOL_VERSION,
      kind: "req",
      id: "11111111-1111-4111-8111-111111111111",
      request: "read_bulk_transfer_chunk",
      params: { transfer_id: "AQIDBAUGBwgJCgsMDQ4PEA", chunk_index: 7 },
    };
    expect(clientEnvelopeSchema.safeParse(base).success).toBe(true);
    expect(
      clientEnvelopeSchema.safeParse({
        ...base,
        params: { ...base.params, chunk_index: 0xffffffff },
      }).success,
    ).toBe(true);
    // One past u32: Rust cannot deserialize it, so neither may the schema.
    expect(
      clientEnvelopeSchema.safeParse({
        ...base,
        params: { ...base.params, chunk_index: 4294967296 },
      }).success,
    ).toBe(false);
    expect(
      clientEnvelopeSchema.safeParse({
        ...base,
        params: { ...base.params, chunk_index: -1 },
      }).success,
    ).toBe(false);
  });
});
