/**
 * Transport-selection state-machine conformance — the nine acceptance matrices.
 *
 * Every test here maps 1:1 to an acceptance criterion in the
 * `remote-transport-selection-state-machine` prompt. The pure reducer, plan
 * computation, caps, retry budget, health, routing, cutover, and multi-path
 * ordering are all exercised with injected time and deterministic ids.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import constantsFixtureJson from "../fixtures/remote-transport-selection/constants.json" with {
  type: "json",
};
import planMatrixFixtureJson from "../fixtures/remote-transport-selection/plan-matrix.json" with {
  type: "json",
};
import tracesFixtureJson from "../fixtures/remote-transport-selection/traces.json" with {
  type: "json",
};
import vocabularyFixtureJson from "../fixtures/remote-transport-selection/vocabulary.json" with {
  type: "json",
};
import {
  buildConnectionLease,
  checkChildCaps,
  computeAuthorizedPlan,
  computeWebRtcHealth,
  computeWebSocketHealth,
  countAllPendingChildren,
  countCurrentChildren,
  countPhysicalChildren,
  evaluateRetryBudget,
  failoverResend,
  iceDisconnectedToReachability,
  initialTransportOrchestratorState,
  isDrainingAllowedMutation,
  isReachabilityCloseReason,
  isTerminalCloseReason,
  isTurnReplacementLeaseValid,
  markReservationTerminal,
  physicalChildCap,
  REMOTE_AUTO_INITIAL_DEADLINE_MAX_SECONDS,
  REMOTE_AUTO_INITIAL_DEADLINE_MIN_SECONDS,
  REMOTE_AUTO_INITIAL_DEADLINE_SECONDS,
  REMOTE_HEALTH_RECOVERY_INTERVALS,
  REMOTE_HEALTH_TIERS,
  REMOTE_IP_CONSENT_CAPABILITIES,
  REMOTE_MAX_CURRENT_WEBRTC,
  REMOTE_MAX_CURRENT_WEBSOCKET,
  REMOTE_MAX_PENDING_CHILDREN_PER_KIND,
  REMOTE_MAX_PENDING_CHILDREN_TOTAL,
  REMOTE_MAX_PHYSICAL_CHILDREN_NORMAL,
  REMOTE_MAX_PHYSICAL_CHILDREN_TURN_REPLACEMENT,
  REMOTE_MAX_RETRIES_PER_KIND,
  REMOTE_ORDINARY_CHILD_STATES,
  REMOTE_PARENT_STATES,
  REMOTE_REACHABILITY_CLASSES,
  REMOTE_REACHABILITY_FALLBACK_CLASSES,
  REMOTE_RESERVATION_TERMINAL_OUTCOMES,
  REMOTE_RETRY_BUDGET_MAX_PER_HOUR,
  REMOTE_RETRY_BUDGET_MAX_PER_TRAIN,
  REMOTE_RETRY_BUDGET_WINDOW_SECONDS,
  REMOTE_RETRY_DELAY_MS,
  REMOTE_RETRY_RESERVATION_SCHEMA,
  REMOTE_ROUTE_LANES,
  REMOTE_SECOND_CHILD_REASONS,
  REMOTE_TERMINAL_CLOSE_REASONS,
  REMOTE_TRAIN_ID_BYTES,
  REMOTE_TRANSPORT_DENIALS,
  REMOTE_TRANSPORT_KINDS,
  REMOTE_TRANSPORT_SELECTION_SCHEMA_VERSION,
  REMOTE_TURN_DRAIN_MAX_SECONDS,
  REMOTE_TURN_LIFECYCLE,
  REMOTE_USER_PREFERENCES,
  REMOTE_WEBRTC_DEGRADED_BUFFER_BYTES,
  REMOTE_WEBRTC_DEGRADED_BUFFER_PROBES,
  REMOTE_WEBRTC_DEGRADED_MISS_PROBES,
  REMOTE_WEBRTC_DISCONNECTED_FAIL_PROBES,
  REMOTE_WEBRTC_FAILED_MISS_PROBES,
  REMOTE_WEBRTC_HEALTHY_SUCCESS_PROBES,
  REMOTE_WEBRTC_PROBE_INTERVAL_SECONDS,
  REMOTE_WEBSOCKET_DEGRADED_BUFFER_BYTES,
  REMOTE_WEBSOCKET_DEGRADED_OLDEST_UNACKED_SECONDS,
  REMOTE_WEBSOCKET_FAILED_RETRANSMISSION,
  type RemoteChildAttemptId,
  type RemoteHealthSample,
  type RemoteIpConsentTriState,
  type RemoteOrdinaryChildState,
  type RemoteParentState,
  type RemoteParticipantPrivacy,
  type RemoteRouteLane,
  type RemoteSecondChildReason,
  type RemoteTransportChild,
  type RemoteTransportCommand,
  type RemoteTransportDenial,
  type RemoteTransportKind,
  type RemoteTransportPlanInput,
  type RemoteTransportRetryReservationV1,
  type RemoteUserPreference,
  retryBudgetOutcomeOutage,
  selectRouteChild,
  transportSelectionReducer,
  validateAutoDeadlineSeconds,
} from "./remote-transport-selection";

// The four fixtures below are generated by the Rust source of truth
// (`cockpit-proto` → vocabulary/constants; `cockpit-core` → plan-matrix/traces)
// and committed under `../fixtures/remote-transport-selection/`. Deleting or
// changing any value on either side fails the corresponding suite.
interface VocabularyFixture {
  readonly transportKinds: readonly string[];
  readonly userPreferences: readonly string[];
  readonly parentStates: readonly string[];
  readonly childStates: readonly string[];
  readonly durableLifecycle: readonly string[];
  readonly reachabilityClasses: readonly string[];
  readonly healthTiers: readonly string[];
  readonly routingClasses: readonly string[];
  readonly secondChildReasons: readonly string[];
  readonly transportDenials: readonly string[];
  readonly reservationOutcomes: readonly string[];
  readonly consentCapabilities: readonly string[];
}
interface ConstantsFixture {
  readonly [key: string]: number;
}
interface PlanMatrixRow {
  readonly name: string;
  readonly input: {
    readonly webrtc_authorized: boolean;
    readonly websocket_authorized: boolean;
    readonly client_supports_webrtc: boolean;
    readonly client_supports_websocket: boolean;
    readonly ip_consent: RemoteIpConsentTriState;
    readonly participant_privacy: RemoteParticipantPrivacy;
    readonly turn_available: boolean;
    readonly quota_available: boolean;
    readonly user_preference: RemoteUserPreference;
  };
  readonly expected: {
    readonly allowed_kinds: readonly RemoteTransportKind[];
    readonly denials: readonly RemoteTransportDenial[];
    readonly preference: RemoteUserPreference;
    readonly turn_required: boolean;
  };
}
interface PlanMatrixFixture {
  readonly rows: readonly PlanMatrixRow[];
}
interface TraceAction {
  readonly kind: string;
  readonly denial?: RemoteTransportDenial;
  readonly [key: string]: unknown;
}
interface TraceEntry {
  readonly step: number;
  readonly input: { readonly kind: string; readonly [key: string]: unknown };
  readonly parent_state_before: RemoteParentState;
  readonly parent_state_after: RemoteParentState;
  readonly actions: readonly TraceAction[];
}
interface TracesFixture {
  readonly scenarios: readonly { readonly name: string; readonly trace: readonly TraceEntry[] }[];
}

const vocabulary = vocabularyFixtureJson as unknown as VocabularyFixture;
const constantsFixture = constantsFixtureJson as unknown as ConstantsFixture;
const planMatrix = planMatrixFixtureJson as unknown as PlanMatrixFixture;
const traces = tracesFixtureJson as unknown as TracesFixture;

/** Map a snake_case plan-matrix input row onto the production plan input. */
function planInputFromRow(row: PlanMatrixRow): RemoteTransportPlanInput {
  return {
    deploymentWebrtc: row.input.webrtc_authorized,
    serviceWebrtc: row.input.webrtc_authorized,
    tenantWebrtc: row.input.webrtc_authorized,
    daemonWebrtc: row.input.webrtc_authorized,
    deploymentWebsocket: row.input.websocket_authorized,
    serviceWebsocket: row.input.websocket_authorized,
    tenantWebsocket: row.input.websocket_authorized,
    daemonWebsocket: row.input.websocket_authorized,
    ipConsent: row.input.ip_consent,
    participantPrivacy: row.input.participant_privacy,
    turnAvailable: row.input.turn_available,
    liveQuota: {
      remainingReservationsThisHour: 0,
      remainingBytes: 0,
      remainingAllocationSeconds: 0,
      exhausted: !row.input.quota_available,
    },
    clientCapabilities: {
      webrtcSupported: row.input.client_supports_webrtc,
      websocketSupported: row.input.client_supports_websocket,
    },
    userPreference: row.input.user_preference,
  };
}

/** Type alias kept for cross-language parity documentation. */
export type TestChildAttemptId = RemoteChildAttemptId;

const fullInput = (
  overrides: Partial<RemoteTransportPlanInput> = {},
): RemoteTransportPlanInput => ({
  deploymentWebrtc: true,
  deploymentWebsocket: true,
  serviceWebrtc: true,
  serviceWebsocket: true,
  tenantWebrtc: true,
  tenantWebsocket: true,
  daemonWebrtc: true,
  daemonWebsocket: true,
  ipConsent: "direct_allowed",
  participantPrivacy: "direct_allowed",
  turnAvailable: true,
  liveQuota: {
    remainingReservationsThisHour: 12,
    remainingBytes: 1024 * 1024 * 1024,
    remainingAllocationSeconds: 28800,
    exhausted: false,
  },
  clientCapabilities: { webrtcSupported: true, websocketSupported: true },
  userPreference: "auto",
  ...overrides,
});

const makeChild = (
  attempt: string,
  kind: RemoteTransportKind,
  state: RemoteOrdinaryChildState,
  extra: Partial<RemoteTransportChild> = {},
): RemoteTransportChild => ({
  childAttemptId: attempt,
  transportKind: kind,
  transportEpoch: `ep_${attempt}`,
  generation: 1,
  state,
  turnLifecycle: state === "active" || state === "degraded" ? "current" : null,
  health: state === "active" ? "healthy" : "degraded",
  consecutiveHealthy: 0,
  consecutiveMisses: 0,
  consecutiveBufferHigh: 0,
  bufferedBytes: 0,
  pendingTimerId: null,
  secondChildReason: null,
  deadlineExpiresAtMs: null,
  closedReason: null,
  ...extra,
});

let attemptCounter = 0;
let epochCounter = 0;
const genCounters: Record<RemoteTransportKind, number> = { webrtc: 0, websocket: 0 };
const resetIds = () => {
  attemptCounter = 0;
  epochCounter = 0;
  genCounters.webrtc = 0;
  genCounters.websocket = 0;
};
const deps = () => ({
  retryBudget: { trainReservations: [], rollingWindowReservations: [] },
  nextChildAttemptId: () => `att_${++attemptCounter}`,
  nextTransportEpoch: () => `ep_${++epochCounter}`,
  nextGeneration: (kind: RemoteTransportKind) => ++genCounters[kind],
  now: () => 0,
});

function isRejected(outcome: {
  status: string;
}): outcome is { status: "rejected"; reason: string } {
  return outcome.status === "rejected";
}

describe("remote_transport_authorized_plan_matrix", () => {
  it("authorizes both kinds when every layer permits and preference is auto", () => {
    const plan = computeAuthorizedPlan(fullInput());
    expect(plan.allowedKinds).toEqual(["webrtc", "websocket"]);
    expect(plan.denials).toEqual([]);
    expect(plan.turnRequired).toBe(false);
  });
  it("denies both with kind_not_authorized when deployment disables both", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ deploymentWebrtc: false, deploymentWebsocket: false }),
    );
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toEqual(["kind_not_authorized"]);
  });
  it("denies both when service disables both kinds", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ serviceWebrtc: false, serviceWebsocket: false }),
    );
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toContain("kind_not_authorized");
  });
  it("denies both when tenant disables both kinds", () => {
    const plan = computeAuthorizedPlan(fullInput({ tenantWebrtc: false, tenantWebsocket: false }));
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toContain("kind_not_authorized");
  });
  it("denies both when daemon disables both kinds", () => {
    const plan = computeAuthorizedPlan(fullInput({ daemonWebrtc: false, daemonWebsocket: false }));
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toContain("kind_not_authorized");
  });
  it("denies with client_capability_missing when client supports neither", () => {
    const plan = computeAuthorizedPlan(
      fullInput({
        clientCapabilities: { webrtcSupported: false, websocketSupported: false },
      }),
    );
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toContain("client_capability_missing");
  });
  it("clears all kinds and denies quota_exhausted on quota exhaustion", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ liveQuota: { ...fullInput().liveQuota, exhausted: true } }),
    );
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toContain("quota_exhausted");
  });
  it("ip-consent unavailable denies BOTH kinds with ip_consent_denied", () => {
    const plan = computeAuthorizedPlan(fullInput({ ipConsent: "unavailable" }));
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toEqual(["ip_consent_denied"]);
  });
  it("marks turnRequired for turn_required privacy and still authorizes webrtc via TURN", () => {
    const plan = computeAuthorizedPlan(fullInput({ participantPrivacy: "turn_required" }));
    expect(plan.turnRequired).toBe(true);
    expect(plan.allowedKinds).toContain("webrtc");
    expect(plan.denials).toEqual([]);
  });
  it("marks turnRequired for relay_only privacy", () => {
    const plan = computeAuthorizedPlan(fullInput({ participantPrivacy: "relay_only" }));
    expect(plan.turnRequired).toBe(true);
  });
  it("turn_required privacy without TURN denies webrtc only; websocket stays", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ participantPrivacy: "turn_required", turnAvailable: false }),
    );
    expect(plan.allowedKinds).not.toContain("webrtc");
    expect(plan.allowedKinds).toContain("websocket");
    expect(plan.denials).toContain("relay_required_turn_unavailable");
  });
  it("relay_only privacy without TURN denies webrtc only; websocket stays", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ participantPrivacy: "relay_only", turnAvailable: false }),
    );
    expect(plan.allowedKinds).not.toContain("webrtc");
    expect(plan.allowedKinds).toContain("websocket");
    expect(plan.denials).toContain("relay_required_turn_unavailable");
  });
  it("relay_only consent without TURN denies webrtc only; websocket stays", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ ipConsent: "relay_only", turnAvailable: false }),
    );
    expect(plan.allowedKinds).not.toContain("webrtc");
    expect(plan.allowedKinds).toContain("websocket");
    expect(plan.denials).toContain("relay_required_turn_unavailable");
  });
  it("relay_only consent with TURN differs observably from direct_allowed", () => {
    const relay = computeAuthorizedPlan(fullInput({ ipConsent: "relay_only" }));
    const direct = computeAuthorizedPlan(fullInput());
    expect(relay).not.toEqual(direct);
    expect(relay.allowedKinds).toContain("webrtc");
    expect(relay.turnRequired).toBe(true);
    expect(direct.turnRequired).toBe(false);
  });
  it("narrows to webrtc only when only webrtc meets", () => {
    const plan = computeAuthorizedPlan(fullInput({ deploymentWebsocket: false }));
    expect(plan.allowedKinds).toContain("webrtc");
    expect(plan.allowedKinds).not.toContain("websocket");
  });
  it("narrows to websocket only when only websocket meets", () => {
    const plan = computeAuthorizedPlan(fullInput({ deploymentWebrtc: false }));
    expect(plan.allowedKinds).not.toContain("webrtc");
    expect(plan.allowedKinds).toContain("websocket");
  });
  it("meet cannot widen: stricter tenant layer removes a kind", () => {
    const plan = computeAuthorizedPlan(fullInput({ tenantWebrtc: false }));
    expect(plan.allowedKinds).not.toContain("webrtc");
    expect(plan.allowedKinds).toContain("websocket");
  });
});

describe("remote_transport_user_preference_matrix", () => {
  it("webrtc preference authorizes webrtc only and never starts fallback", () => {
    const plan = computeAuthorizedPlan(fullInput({ userPreference: "webrtc" }));
    expect(plan.allowedKinds).toEqual(["webrtc"]);
  });
  it("websocket preference authorizes websocket only", () => {
    const plan = computeAuthorizedPlan(fullInput({ userPreference: "websocket" }));
    expect(plan.allowedKinds).toEqual(["websocket"]);
  });
  it("auto authorizes both when available", () => {
    const plan = computeAuthorizedPlan(fullInput({ userPreference: "auto" }));
    expect(plan.allowedKinds).toEqual(["webrtc", "websocket"]);
  });
  it("webrtc preference with webrtc unavailable returns preference_disallowed, no silent override", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ userPreference: "webrtc", deploymentWebrtc: false }),
    );
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toContain("preference_disallowed");
  });
  it("websocket preference with websocket unavailable returns preference_disallowed", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ userPreference: "websocket", deploymentWebsocket: false }),
    );
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toContain("preference_disallowed");
  });
  it("auto with neither available returns kind_not_authorized, never silent", () => {
    const plan = computeAuthorizedPlan(
      fullInput({ userPreference: "auto", deploymentWebrtc: false, deploymentWebsocket: false }),
    );
    expect(plan.allowedKinds).toEqual([]);
    expect(plan.denials).toEqual(["kind_not_authorized"]);
  });
  it("webrtc preference does not widen to websocket even if websocket is available", () => {
    const plan = computeAuthorizedPlan(fullInput({ userPreference: "webrtc" }));
    expect(plan.allowedKinds).not.toContain("websocket");
  });
});

describe("remote_transport_only_reachability_falls_back", () => {
  it("terminal close reasons never fall back", () => {
    for (const reason of REMOTE_TERMINAL_CLOSE_REASONS) {
      expect(isTerminalCloseReason(reason)).toBe(true);
      expect(isReachabilityCloseReason(reason)).toBe(false);
    }
  });
  it("reachability close reasons may fall back", () => {
    const reachability = [
      "ice_no_candidate_pair",
      "ice_timeout",
      "network_unreachable",
      "turn_unreachable",
    ] as const;
    for (const reason of reachability) {
      expect(isReachabilityCloseReason(reason)).toBe(true);
      expect(isTerminalCloseReason(reason)).toBe(false);
    }
  });
  it("ice_disconnected maps to network_unreachable after 3 consecutive failed probes", () => {
    expect(iceDisconnectedToReachability(0)).toBeNull();
    expect(iceDisconnectedToReachability(2)).toBeNull();
    expect(iceDisconnectedToReachability(3)).toBe("network_unreachable");
    expect(iceDisconnectedToReachability(4)).toBe("network_unreachable");
  });
  it("default deadline is exactly 10 seconds", () => {
    expect(REMOTE_AUTO_INITIAL_DEADLINE_SECONDS).toBe(10);
  });
  it("deadline range is exactly 3..30 seconds inclusive", () => {
    expect(REMOTE_AUTO_INITIAL_DEADLINE_MIN_SECONDS).toBe(3);
    expect(REMOTE_AUTO_INITIAL_DEADLINE_MAX_SECONDS).toBe(30);
    expect(validateAutoDeadlineSeconds(2)).toEqual({ ok: false, reason: "out_of_range" });
    expect(validateAutoDeadlineSeconds(3)).toEqual({ ok: true });
    expect(validateAutoDeadlineSeconds(30)).toEqual({ ok: true });
    expect(validateAutoDeadlineSeconds(31)).toEqual({ ok: false, reason: "out_of_range" });
    expect(validateAutoDeadlineSeconds(10.5)).toEqual({ ok: false, reason: "out_of_range" });
  });
  it("auto starts websocket after deadline fires with no active webrtc", () => {
    resetIds();
    const d = deps();
    let now = 0;
    d.now = () => now;
    let state = initialTransportOrchestratorState();
    const result = transportSelectionReducer(
      state,
      { kind: "plan_requested", atMs: 0, input: fullInput(), trainId: "train_1" },
      d,
    );
    state = result.state;
    const startCmd = result.commands.find((c) => c.kind === "start_child");
    expect(startCmd).toBeDefined();
    const deadlineCmd = result.commands.find((c) => c.kind === "schedule_deadline_timer");
    expect(deadlineCmd).toBeDefined();
    const attempt = (startCmd as { childAttemptId: string }).childAttemptId;
    state = transportSelectionReducer(
      state,
      {
        kind: "child_attempt_reserved",
        atMs: 0,
        childAttemptId: attempt,
        transportKind: "webrtc",
        transportEpoch: "ep_1",
        generation: 1,
        reservation: {} as RemoteTransportRetryReservationV1,
      },
      d,
    ).state;
    now = 10000;
    const timerId = (deadlineCmd as { timerId: string }).timerId;
    const fireResult = transportSelectionReducer(
      state,
      { kind: "deadline_timer_fired", atMs: now, timerId, childAttemptId: attempt },
      d,
    );
    const wsStart = fireResult.commands.find(
      (c) =>
        c.kind === "start_child" && (c as { transportKind: string }).transportKind === "websocket",
    );
    expect(wsStart).toBeDefined();
  });
  it("auto does not start websocket after deadline if webrtc is active", () => {
    resetIds();
    const d = deps();
    let now = 0;
    d.now = () => now;
    let state = initialTransportOrchestratorState();
    const result = transportSelectionReducer(
      state,
      { kind: "plan_requested", atMs: 0, input: fullInput(), trainId: "train_1" },
      d,
    );
    state = result.state;
    const startCmd = result.commands.find((c) => c.kind === "start_child") as {
      childAttemptId: string;
      transportKind: string;
    };
    const deadlineCmd = result.commands.find((c) => c.kind === "schedule_deadline_timer") as {
      timerId: string;
      childAttemptId: string;
    };
    state = transportSelectionReducer(
      state,
      {
        kind: "child_attempt_reserved",
        atMs: 0,
        childAttemptId: startCmd.childAttemptId,
        transportKind: "webrtc",
        transportEpoch: "ep_1",
        generation: 1,
        reservation: {} as RemoteTransportRetryReservationV1,
      },
      d,
    ).state;
    state = transportSelectionReducer(
      state,
      {
        kind: "child_active",
        atMs: 5000,
        childAttemptId: startCmd.childAttemptId,
      },
      d,
    ).state;
    now = 10000;
    const fireResult = transportSelectionReducer(
      state,
      {
        kind: "deadline_timer_fired",
        atMs: now,
        timerId: deadlineCmd.timerId,
        childAttemptId: startCmd.childAttemptId,
      },
      d,
    );
    const wsStart = fireResult.commands.find(
      (c) =>
        c.kind === "start_child" && (c as { transportKind: string }).transportKind === "websocket",
    );
    expect(wsStart).toBeUndefined();
  });
});

describe("remote_transport_child_caps_and_reasons", () => {
  it("at most one routed-current webrtc child", () => {
    expect(REMOTE_MAX_CURRENT_WEBRTC).toBe(1);
    expect(checkChildCaps([makeChild("a", "webrtc", "active")], "webrtc", false)).toEqual({
      ok: false,
      reason: "current_cap_exceeded",
    });
  });
  it("at most one routed-current websocket child", () => {
    expect(REMOTE_MAX_CURRENT_WEBSOCKET).toBe(1);
    expect(checkChildCaps([makeChild("a", "websocket", "active")], "websocket", false)).toEqual({
      ok: false,
      reason: "current_cap_exceeded",
    });
  });
  it("at most two ordinary pending children total", () => {
    expect(REMOTE_MAX_PENDING_CHILDREN_TOTAL).toBe(2);
    const children = [
      makeChild("a", "webrtc", "pending", { turnLifecycle: null }),
      makeChild("b", "websocket", "pending", { turnLifecycle: null }),
    ];
    expect(countAllPendingChildren(children)).toBe(2);
  });
  it("at most one pending child per kind", () => {
    expect(REMOTE_MAX_PENDING_CHILDREN_PER_KIND).toBe(1);
    expect(
      checkChildCaps(
        [makeChild("a", "webrtc", "pending", { turnLifecycle: null })],
        "webrtc",
        false,
      ),
    ).toEqual({
      ok: false,
      reason: "pending_cap_per_kind_exceeded",
    });
  });
  it("physical cap is two normally and three during TURN replacement", () => {
    expect(REMOTE_MAX_PHYSICAL_CHILDREN_NORMAL).toBe(2);
    expect(REMOTE_MAX_PHYSICAL_CHILDREN_TURN_REPLACEMENT).toBe(3);
    expect(physicalChildCap(false)).toBe(2);
    expect(physicalChildCap(true)).toBe(3);
  });
  it("TURN replacement allows a second webrtc child (replacement_pending)", () => {
    expect(checkChildCaps([makeChild("a", "webrtc", "active")], "webrtc", true)).toEqual({
      ok: true,
    });
  });
  it("only one replacement_pending TURN child at a time", () => {
    const children = [
      makeChild("a", "webrtc", "active"),
      makeChild("b", "webrtc", "pending", { turnLifecycle: "replacement_pending" }),
    ];
    expect(checkChildCaps(children, "webrtc", true)).toEqual({
      ok: false,
      reason: "turn_replacement_already_pending",
    });
  });
  it("exactly one current plus one replacement_pending or draining pair", () => {
    expect(REMOTE_SECOND_CHILD_REASONS).toEqual([
      "preferred_path_recovery",
      "network_handoff",
      "operator_force",
      "degraded_path_replacement",
      "credential_rotation",
    ]);
  });
  it("a second child is only allowed for named reasons, not speculative racing", () => {
    const allReasons = new Set<string>(REMOTE_SECOND_CHILD_REASONS);
    expect(allReasons.has("credential_rotation")).toBe(true);
    expect(allReasons.has("speculative")).toBe(false);
  });
  it("countCurrentChildren excludes draining", () => {
    const children = [
      makeChild("a", "webrtc", "active"),
      makeChild("b", "webrtc", "active", { turnLifecycle: "draining" }),
    ];
    expect(countCurrentChildren(children, "webrtc")).toBe(1);
  });
  it("countPhysicalChildren excludes draining", () => {
    const children = [
      makeChild("a", "webrtc", "active"),
      makeChild("b", "webrtc", "active", { turnLifecycle: "draining" }),
    ];
    expect(countPhysicalChildren(children)).toBe(1);
  });
});

describe("remote_transport_retry_budget", () => {
  const baseRequest = {
    trainId: "train_1",
    transportKind: "webrtc" as RemoteTransportKind,
    childAttemptId: "att_1",
    reservationType: "initial" as const,
  };
  it("schema is RemoteTransportRetryReservation with 16-byte train id", () => {
    expect(REMOTE_RETRY_RESERVATION_SCHEMA).toBe("RemoteTransportRetryReservation");
  });
  it("reserves an initial child idempotently", () => {
    const outcome = evaluateRetryBudget(
      { trainReservations: [], rollingWindowReservations: [] },
      baseRequest,
      0,
    );
    expect(outcome.status).toBe("reserved");
    if (outcome.status === "reserved") {
      expect(outcome.reservation.reservationType).toBe("initial");
      expect(outcome.reservation.trainId).toBe("train_1");
    }
  });
  it("exact duplicate by child attempt is idempotent and does not count twice", () => {
    const first = evaluateRetryBudget(
      { trainReservations: [], rollingWindowReservations: [] },
      baseRequest,
      0,
    );
    if (first.status !== "reserved") throw new Error("expected reserved");
    const snapshot = {
      trainReservations: [first.reservation],
      rollingWindowReservations: [first.reservation],
    };
    expect(evaluateRetryBudget(snapshot, baseRequest, 1000).status).toBe("duplicate");
  });
  it("rejects more than four reservations per train", () => {
    expect(REMOTE_RETRY_BUDGET_MAX_PER_TRAIN).toBe(4);
    const reservations: RemoteTransportRetryReservationV1[] = Array.from({ length: 4 }, (_, i) => ({
      schemaVersion: 1 as const,
      reservationId: `res_${i}`,
      tenantId: "",
      accountId: "",
      clientDeviceId: "",
      logicalAttachmentId: "",
      trainId: "train_1",
      transportKind: "webrtc",
      childAttemptId: `att_${i}`,
      reservationType: "initial" as const,
      reservedAtMs: 0,
      expiresAtMs: 9999,
      terminalOutcome: null,
      terminalAtMs: null,
    }));
    const outcome = evaluateRetryBudget(
      { trainReservations: reservations, rollingWindowReservations: [] },
      { ...baseRequest, childAttemptId: "att_new" },
      100,
    );
    expect(isRejected(outcome)).toBe(true);
    if (isRejected(outcome)) expect(outcome.reason).toBe("max_per_train_exceeded");
  });
  it("rejects twelve committed reservations in the preceding rolling 3600 seconds", () => {
    expect(REMOTE_RETRY_BUDGET_MAX_PER_HOUR).toBe(12);
    expect(REMOTE_RETRY_BUDGET_WINDOW_SECONDS).toBe(3600);
    const now = 10_000_000;
    const reservations: RemoteTransportRetryReservationV1[] = Array.from(
      { length: 12 },
      (_, i) => ({
        schemaVersion: 1 as const,
        reservationId: `res_${i}`,
        tenantId: "",
        accountId: "",
        clientDeviceId: "",
        logicalAttachmentId: "",
        trainId: `train_${i}`,
        transportKind: "webrtc",
        childAttemptId: `att_${i}`,
        reservationType: "initial" as const,
        reservedAtMs: now - 1000,
        expiresAtMs: now + 9999,
        terminalOutcome: null,
        terminalAtMs: null,
      }),
    );
    const outcome = evaluateRetryBudget(
      { trainReservations: [], rollingWindowReservations: reservations },
      { ...baseRequest, trainId: "train_new", childAttemptId: "att_new" },
      now,
    );
    expect(isRejected(outcome)).toBe(true);
    if (isRejected(outcome)) expect(outcome.reason).toBe("max_per_hour_exceeded");
  });
  it("initial plus one fresh retry per kind — second retry is exhausted", () => {
    expect(REMOTE_MAX_RETRIES_PER_KIND).toBe(1);
    const retryRes: RemoteTransportRetryReservationV1 = {
      schemaVersion: 1,
      reservationId: "res_r1",
      tenantId: "",
      accountId: "",
      clientDeviceId: "",
      logicalAttachmentId: "",
      trainId: "train_1",
      transportKind: "webrtc",
      childAttemptId: "att_r1",
      reservationType: "retry",
      reservedAtMs: 0,
      expiresAtMs: 9999,
      terminalOutcome: null,
      terminalAtMs: null,
    };
    const outcome = evaluateRetryBudget(
      { trainReservations: [retryRes], rollingWindowReservations: [] },
      { ...baseRequest, childAttemptId: "att_r2", reservationType: "retry" },
      100,
    );
    expect(isRejected(outcome)).toBe(true);
    if (isRejected(outcome)) expect(outcome.reason).toBe("kind_retry_exhausted");
  });
  it("retry delay is injected exponential 1 second then no further same-kind retry", () => {
    expect(REMOTE_RETRY_DELAY_MS).toBe(1000);
  });
  it("markReservationTerminal writes terminal outcome for cleanup", () => {
    const res: RemoteTransportRetryReservationV1 = {
      schemaVersion: 1,
      reservationId: "res_1",
      tenantId: "",
      accountId: "",
      clientDeviceId: "",
      logicalAttachmentId: "",
      trainId: "train_1",
      transportKind: "webrtc",
      childAttemptId: "att_1",
      reservationType: "initial",
      reservedAtMs: 0,
      expiresAtMs: 9999,
      terminalOutcome: null,
      terminalAtMs: null,
    };
    const terminal = markReservationTerminal(res, "cancelled", 5000);
    expect(terminal.terminalOutcome).toBe("cancelled");
    expect(terminal.terminalAtMs).toBe(5000);
    // The `failed` terminal outcome (Rust `ReservationOutcome::Failed`) is an
    // accepted input and round-trips onto the reservation.
    const failed = markReservationTerminal(res, "failed", 6000);
    expect(failed.terminalOutcome).toBe("failed");
    expect(REMOTE_RESERVATION_TERMINAL_OUTCOMES).toContain("failed");
  });
  it("database outage denies new children but is a typed rejection", () => {
    const outcome = retryBudgetOutcomeOutage();
    expect(isRejected(outcome)).toBe(true);
    if (isRejected(outcome)) expect(outcome.reason).toBe("database_outage");
  });
  it("reservations outside the rolling window do not count", () => {
    const now = 10_000_000;
    const old: RemoteTransportRetryReservationV1 = {
      schemaVersion: 1,
      reservationId: "res_old",
      tenantId: "",
      accountId: "",
      clientDeviceId: "",
      logicalAttachmentId: "",
      trainId: "train_old",
      transportKind: "webrtc",
      childAttemptId: "att_old",
      reservationType: "initial",
      reservedAtMs: now - (REMOTE_RETRY_BUDGET_WINDOW_SECONDS + 1) * 1000,
      expiresAtMs: 0,
      terminalOutcome: "cancelled",
      terminalAtMs: now - (REMOTE_RETRY_BUDGET_WINDOW_SECONDS + 1) * 1000,
    };
    const outcome = evaluateRetryBudget(
      { trainReservations: [], rollingWindowReservations: [old] },
      { ...baseRequest, childAttemptId: "att_new" },
      now,
    );
    expect(outcome.status).toBe("reserved");
  });
});

describe("remote_transport_health_thresholds", () => {
  it("WebRTC probe interval is exactly 5 seconds", () => {
    expect(REMOTE_WEBRTC_PROBE_INTERVAL_SECONDS).toBe(5);
  });
  it("WebRTC healthy after two consecutive successes", () => {
    expect(REMOTE_WEBRTC_HEALTHY_SUCCESS_PROBES).toBe(2);
    const child = makeChild("a", "webrtc", "degraded", { consecutiveHealthy: 0 });
    const probe: RemoteHealthSample = {
      kind: "webrtc",
      childAttemptId: "a",
      atMs: 1000,
      success: true,
      bufferedBytes: 0,
    };
    let r = computeWebRtcHealth(child, probe);
    expect(r.consecutiveHealthy).toBe(1);
    expect(r.health).toBe("degraded");
    r = computeWebRtcHealth({ ...child, consecutiveHealthy: 1 }, probe);
    expect(r.consecutiveHealthy).toBe(2);
    expect(r.health).toBe("healthy");
  });
  it("WebRTC degraded after three misses", () => {
    expect(REMOTE_WEBRTC_DEGRADED_MISS_PROBES).toBe(3);
    const child = makeChild("a", "webrtc", "active", { consecutiveMisses: 2 });
    const r = computeWebRtcHealth(child, {
      kind: "webrtc",
      childAttemptId: "a",
      atMs: 1000,
      success: false,
      bufferedBytes: 0,
    });
    expect(r.consecutiveMisses).toBe(3);
    expect(r.health).toBe("degraded");
  });
  it("WebRTC degraded when a failing probe stays buffered >= 4 MiB for two probes", () => {
    expect(REMOTE_WEBRTC_DEGRADED_BUFFER_BYTES).toBe(4 * 1024 * 1024);
    expect(REMOTE_WEBRTC_DEGRADED_BUFFER_PROBES).toBe(2);
    // Buffer backpressure is liveness-independent: the high-buffer streak
    // advances on any probe whose buffered bytes exceed the threshold — a failed
    // probe here — matching the Rust `reduce_webrtc_probe`.
    const child = makeChild("a", "webrtc", "active", {
      consecutiveBufferHigh: 1,
      consecutiveMisses: 0,
    });
    const r = computeWebRtcHealth(child, {
      kind: "webrtc",
      childAttemptId: "a",
      atMs: 1000,
      success: false,
      bufferedBytes: 4 * 1024 * 1024,
    });
    expect(r.consecutiveBufferHigh).toBe(2);
    expect(r.health).toBe("degraded");
  });
  it("WebRTC high buffer degrades even on a SUCCESSFUL probe (backpressure is liveness-independent)", () => {
    // The Rust `reduce_webrtc_probe` advances `consecutive_high_buffer_probes`
    // on ANY high-buffer probe, success included — a live child that keeps its
    // send buffer above the threshold for two probes is degraded even though its
    // liveness checks pass. The prior TS behavior wrongly drained the streak on a
    // successful probe, diverging from the source of truth; this pins the fix.
    const child = makeChild("a", "webrtc", "active", {
      consecutiveBufferHigh: 1,
      health: "healthy",
      consecutiveHealthy: 1,
    });
    const r = computeWebRtcHealth(child, {
      kind: "webrtc",
      childAttemptId: "a",
      atMs: 1000,
      success: true,
      bufferedBytes: 8 * 1024 * 1024,
    });
    expect(r.consecutiveBufferHigh).toBe(2);
    expect(r.health).toBe("degraded");
  });
  it("WebRTC failed after six misses", () => {
    expect(REMOTE_WEBRTC_FAILED_MISS_PROBES).toBe(6);
    const child = makeChild("a", "webrtc", "degraded", { consecutiveMisses: 5 });
    const r = computeWebRtcHealth(child, {
      kind: "webrtc",
      childAttemptId: "a",
      atMs: 1000,
      success: false,
      bufferedBytes: 0,
    });
    expect(r.consecutiveMisses).toBe(6);
    expect(r.health).toBe("failed");
  });
  it("ice_disconnected fail threshold is 3 probes", () => {
    expect(REMOTE_WEBRTC_DISCONNECTED_FAIL_PROBES).toBe(3);
  });
  it("WebSocket degraded when oldest unacked age >= 3 seconds", () => {
    expect(REMOTE_WEBSOCKET_DEGRADED_OLDEST_UNACKED_SECONDS).toBe(3);
    const r = computeWebSocketHealth(makeChild("a", "websocket", "active"), {
      kind: "websocket",
      childAttemptId: "a",
      atMs: 1000,
      oldestUnackedAgeSeconds: 3,
      bufferedBytes: 0,
      retransmissionCount: 0,
    });
    expect(r.health).toBe("degraded");
  });
  it("WebSocket degraded when buffered bytes >= 4 MiB", () => {
    expect(REMOTE_WEBSOCKET_DEGRADED_BUFFER_BYTES).toBe(4 * 1024 * 1024);
    const r = computeWebSocketHealth(makeChild("a", "websocket", "active"), {
      kind: "websocket",
      childAttemptId: "a",
      atMs: 1000,
      oldestUnackedAgeSeconds: 0,
      bufferedBytes: 4 * 1024 * 1024,
      retransmissionCount: 0,
    });
    expect(r.health).toBe("degraded");
  });
  it("WebSocket failed at the third retransmission", () => {
    expect(REMOTE_WEBSOCKET_FAILED_RETRANSMISSION).toBe(3);
    const r = computeWebSocketHealth(makeChild("a", "websocket", "degraded"), {
      kind: "websocket",
      childAttemptId: "a",
      atMs: 1000,
      oldestUnackedAgeSeconds: 0,
      bufferedBytes: 0,
      retransmissionCount: 3,
    });
    expect(r.health).toBe("failed");
  });
  it("recovery requires two consecutive healthy intervals", () => {
    expect(REMOTE_HEALTH_RECOVERY_INTERVALS).toBe(2);
    const child = makeChild("a", "websocket", "degraded", { consecutiveHealthy: 0 });
    const ok: RemoteHealthSample = {
      kind: "websocket",
      childAttemptId: "a",
      atMs: 1000,
      oldestUnackedAgeSeconds: 0,
      bufferedBytes: 0,
      retransmissionCount: 0,
    };
    let r = computeWebSocketHealth(child, ok);
    expect(r.consecutiveHealthy).toBe(1);
    expect(r.health).toBe("degraded");
    r = computeWebSocketHealth({ ...child, consecutiveHealthy: 1 }, ok);
    expect(r.consecutiveHealthy).toBe(2);
    expect(r.health).toBe("healthy");
  });
});

describe("remote_transport_route_trace", () => {
  it("control chooses healthy over degraded, then lower epoch", () => {
    const children = [
      makeChild("a", "webrtc", "degraded", { transportEpoch: "ep_1" }),
      makeChild("b", "websocket", "active", { transportEpoch: "ep_2" }),
    ];
    expect(selectRouteChild(children, "control")?.childAttemptId).toBe("b");
  });
  it("control ties by lower transport epoch among healthy", () => {
    const children = [
      makeChild("a", "webrtc", "active", { transportEpoch: "ep_3" }),
      makeChild("b", "websocket", "active", { transportEpoch: "ep_2" }),
    ];
    expect(selectRouteChild(children, "control")?.transportEpoch).toBe("ep_2");
  });
  it("interactive chooses healthy webrtc first", () => {
    const children = [
      makeChild("a", "websocket", "active", { transportEpoch: "ep_1" }),
      makeChild("b", "webrtc", "active", { transportEpoch: "ep_2" }),
    ];
    expect(selectRouteChild(children, "interactive")?.transportKind).toBe("webrtc");
  });
  it("interactive chooses healthy websocket if no healthy webrtc", () => {
    const children = [
      makeChild("a", "webrtc", "degraded", { transportEpoch: "ep_1" }),
      makeChild("b", "websocket", "active", { transportEpoch: "ep_2" }),
    ];
    expect(selectRouteChild(children, "interactive")?.transportKind).toBe("websocket");
  });
  it("interactive falls to degraded by lower epoch when no healthy", () => {
    const children = [
      makeChild("a", "webrtc", "degraded", { transportEpoch: "ep_3" }),
      makeChild("b", "websocket", "degraded", { transportEpoch: "ep_1" }),
    ];
    expect(selectRouteChild(children, "interactive")?.transportEpoch).toBe("ep_1");
  });
  it("bulk chooses healthy child with more writable bytes, tie webrtc", () => {
    // Equal buffered bytes → equal writable capacity → WebRTC wins the tie.
    const children = [
      makeChild("a", "websocket", "active", { transportEpoch: "ep_1", bufferedBytes: 2048 }),
      makeChild("b", "webrtc", "active", { transportEpoch: "ep_2", bufferedBytes: 2048 }),
    ];
    expect(selectRouteChild(children, "bulk")?.transportKind).toBe("webrtc");
  });
  it("bulk chooses more writable bytes (least buffered)", () => {
    // Writable capacity is derived from buffered bytes (Rust `writable_bytes()`):
    // the WebSocket child is far less buffered, so it wins despite the WebRTC tie
    // preference.
    const children = [
      makeChild("a", "webrtc", "active", {
        transportEpoch: "ep_1",
        bufferedBytes: 8 * 1024 * 1024,
      }),
      makeChild("b", "websocket", "active", { transportEpoch: "ep_2", bufferedBytes: 0 }),
    ];
    expect(selectRouteChild(children, "bulk")?.childAttemptId).toBe("b");
  });
  it("replacement_pending is never selected", () => {
    const children = [
      makeChild("a", "webrtc", "active", {
        transportEpoch: "ep_1",
        turnLifecycle: "replacement_pending",
      }),
      makeChild("b", "websocket", "degraded", { transportEpoch: "ep_2" }),
    ];
    expect(selectRouteChild(children, "control")?.childAttemptId).toBe("b");
  });
  it("draining is never selected for new work", () => {
    const children = [
      makeChild("a", "webrtc", "active", { transportEpoch: "ep_1", turnLifecycle: "draining" }),
      makeChild("b", "websocket", "active", { transportEpoch: "ep_2" }),
    ];
    expect(selectRouteChild(children, "control")?.childAttemptId).toBe("b");
  });
  it("draining may carry only already-assigned replay/ACK/control", () => {
    const drainingChild = makeChild("a", "webrtc", "active", { turnLifecycle: "draining" });
    const assigned = new Set(["del_1"]);
    expect(isDrainingAllowedMutation(drainingChild, "del_1", assigned).allowed).toBe(true);
    expect(isDrainingAllowedMutation(drainingChild, "del_new", assigned)).toEqual({
      allowed: false,
      reason: "child_draining",
    });
  });
  it("lease+supervisor-ACK cutover: lease is valid with one current + one draining", () => {
    expect(
      isTurnReplacementLeaseValid({
        currentChildAttemptIds: ["a"],
        drainingChildAttemptIds: ["b"],
      }),
    ).toBe(true);
    expect(
      isTurnReplacementLeaseValid({ currentChildAttemptIds: ["a"], drainingChildAttemptIds: [] }),
    ).toBe(false);
  });
  it("TURN drain max is 30 seconds", () => {
    expect(REMOTE_TURN_DRAIN_MAX_SECONDS).toBe(30);
  });
  it("one stable delivery ID is assigned to one current child", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active",
      children: [makeChild("a", "webrtc", "active")],
    };
    const result = transportSelectionReducer(
      state,
      {
        kind: "route_request",
        atMs: 100,
        deliveryId: "del_1",
        lane: "interactive",
        payloadBytes: 64,
      },
      d,
    );
    expect(result.commands.find((c) => c.kind === "route_delivery")).toBeDefined();
    expect(result.state.deliveryAssignments.get("del_1")).toBe("a");
  });
  it("exact failover resend uses the same delivery id", () => {
    const cmd = failoverResend("del_1", "child_b");
    expect(cmd.kind).toBe("failover_resend");
    if (cmd.kind === "failover_resend") {
      expect(cmd.deliveryId).toBe("del_1");
      expect(cmd.targetChildAttemptId).toBe("child_b");
    }
  });
  it("delivery dedupe: ledger records each delivery to a child once", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active",
      children: [makeChild("a", "webrtc", "active")],
    };
    state = transportSelectionReducer(
      state,
      {
        kind: "route_request",
        atMs: 100,
        deliveryId: "del_1",
        lane: "interactive",
        payloadBytes: 64,
      },
      d,
    ).state;
    const before = state.ledgerDeliveries.get("del_1")?.length ?? 0;
    state = transportSelectionReducer(
      state,
      {
        kind: "route_request",
        atMs: 200,
        deliveryId: "del_1",
        lane: "interactive",
        payloadBytes: 64,
      },
      d,
    ).state;
    expect(state.ledgerDeliveries.get("del_1")?.length ?? 0).toBe(before);
  });
});

describe("remote_transport_multi_path_ordering", () => {
  it("all mutations from permitted children enter the ledger", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active",
      children: [makeChild("a", "webrtc", "active"), makeChild("b", "websocket", "active")],
    };
    state = transportSelectionReducer(
      state,
      {
        kind: "route_request",
        atMs: 100,
        deliveryId: "del_1",
        lane: "interactive",
        payloadBytes: 64,
      },
      d,
    ).state;
    state = transportSelectionReducer(
      state,
      { kind: "route_request", atMs: 200, deliveryId: "del_2", lane: "bulk", payloadBytes: 1024 },
      d,
    ).state;
    expect(state.ledgerDeliveries.size).toBe(2);
  });
  it("concurrent reads and closes do not clear other children or budget", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active",
      children: [makeChild("a", "webrtc", "active"), makeChild("b", "websocket", "active")],
    };
    state = transportSelectionReducer(
      state,
      { kind: "child_closed", atMs: 100, childAttemptId: "a", reason: "network_unreachable" },
      d,
    ).state;
    expect(state.children.find((c) => c.childAttemptId === "b")?.state).toBe("active");
  });
  it("closing one child does not clear delivery assignments", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active",
      children: [makeChild("a", "webrtc", "active")],
    };
    state = transportSelectionReducer(
      state,
      {
        kind: "route_request",
        atMs: 100,
        deliveryId: "del_1",
        lane: "interactive",
        payloadBytes: 64,
      },
      d,
    ).state;
    state = transportSelectionReducer(
      state,
      { kind: "child_closed", atMs: 200, childAttemptId: "a", reason: "local_close" },
      d,
    ).state;
    expect(state.deliveryAssignments.get("del_1")).toBe("a");
  });
});

describe("remote_transport_deadline_late_success_race", () => {
  it("late cancelled child cannot activate", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "establishing",
      children: [makeChild("a", "webrtc", "closing", { deadlineExpiresAtMs: 10000 })],
    };
    const result = transportSelectionReducer(
      state,
      { kind: "child_active", atMs: 12000, childAttemptId: "a" },
      d,
    );
    expect(result.state.children.find((c) => c.childAttemptId === "a")?.state).toBe("closing");
  });
  it("deadline fires then late ICE success serializes by generation — ws already started", () => {
    resetIds();
    const d = deps();
    let now = 0;
    d.now = () => now;
    let state = initialTransportOrchestratorState();
    const planResult = transportSelectionReducer(
      state,
      { kind: "plan_requested", atMs: 0, input: fullInput(), trainId: "train_1" },
      d,
    );
    state = planResult.state;
    const startCmd = planResult.commands.find((c) => c.kind === "start_child") as {
      childAttemptId: string;
    };
    const deadlineCmd = planResult.commands.find((c) => c.kind === "schedule_deadline_timer") as {
      timerId: string;
      childAttemptId: string;
    };
    state = transportSelectionReducer(
      state,
      {
        kind: "child_attempt_reserved",
        atMs: 0,
        childAttemptId: startCmd.childAttemptId,
        transportKind: "webrtc",
        transportEpoch: "ep_1",
        generation: 1,
        reservation: {} as RemoteTransportRetryReservationV1,
      },
      d,
    ).state;
    now = 10000;
    const fireResult = transportSelectionReducer(
      state,
      {
        kind: "deadline_timer_fired",
        atMs: now,
        timerId: deadlineCmd.timerId,
        childAttemptId: startCmd.childAttemptId,
      },
      d,
    );
    state = fireResult.state;
    expect(
      fireResult.commands.find(
        (c) =>
          c.kind === "start_child" &&
          (c as { transportKind: string }).transportKind === "websocket",
      ),
    ).toBeDefined();
    const lateActive = transportSelectionReducer(
      state,
      {
        kind: "child_active",
        atMs: 10500,
        childAttemptId: startCmd.childAttemptId,
      },
      d,
    );
    expect(
      lateActive.state.children.find((c) => c.childAttemptId === startCmd.childAttemptId)?.state,
    ).toBe("active");
  });
  it("separately authorized kinds may coexist", () => {
    resetIds();
    const state = {
      ...initialTransportOrchestratorState(),
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active" as const,
      children: [makeChild("a", "webrtc", "active"), makeChild("b", "websocket", "active")],
    };
    expect(state.children.length).toBe(2);
    expect(state.children.every((c) => c.state === "active")).toBe(true);
  });
  it("background/cancel/revoke/supersede aborts all pending timers", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "establishing",
      children: [makeChild("a", "webrtc", "pending")],
      pendingTimers: ["deadline_a", "liveness_a"],
    };
    const result = transportSelectionReducer(state, { kind: "cancel", atMs: 5000 }, d);
    expect(result.state.pendingTimers).toEqual([]);
    expect(result.state.parentState).toBe("cancelled");
    expect(result.commands.filter((c) => c.kind === "cancel_timer").length).toBe(2);
  });
  it("supersede transitions parent to superseded and aborts timers", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active",
      children: [makeChild("a", "webrtc", "active")],
      pendingTimers: ["t1"],
    };
    const result = transportSelectionReducer(state, { kind: "supersede", atMs: 5000 }, d);
    expect(result.state.parentState).toBe("superseded");
    expect(result.state.pendingTimers).toEqual([]);
  });
  it("no retry survives background/cancel/revoke/supersede", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "establishing",
      children: [makeChild("a", "webrtc", "pending")],
      pendingTimers: ["retry_a"],
      pendingRetry: { kind: "webrtc", childAttemptId: "att_pending", transportEpoch: "ep_pending" },
    };
    const result = transportSelectionReducer(state, { kind: "revoke", atMs: 5000 }, d);
    expect(result.commands.find((c) => c.kind === "schedule_retry")).toBeUndefined();
    expect(result.state.pendingTimers).toEqual([]);
  });
});

describe("remote transport selection schema parity", () => {
  it("exports the cross-language schema version", () => {
    expect(REMOTE_TRANSPORT_SELECTION_SCHEMA_VERSION).toBe(1);
  });
});

describe("remote_transport_selection_round3_regressions", () => {
  // H2 — credential_rotation_lead must never start unauthorized WebRTC. The
  // dedicated event mirrors the Rust `reduce_credential_rotation` and enforces
  // the authorized plan, so a WebSocket-only plan yields no WebRTC replacement.
  it("credential_rotation_lead is inert under a WebSocket-only plan (no WebRTC start)", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["websocket"],
        denials: ["relay_required_turn_unavailable"],
        preference: "auto",
        turnRequired: true,
      },
      parentState: "active",
      children: [makeChild("w", "webrtc", "active")],
    };
    const r = transportSelectionReducer(state, { kind: "credential_rotation_lead", atMs: 1000 }, d);
    expect(r.commands).toEqual([]);
    expect(r.state.children).toHaveLength(1);
    expect(r.state.children.find((c) => c.childAttemptId === "w")?.state).toBe("active");
  });

  // H3 — a cancelled/superseded/backgrounded retry must not start after a stale
  // `retry_delay_fired`: the retry timer is tracked, the pending retry cleared.
  for (const terminal of ["cancel", "revoke", "supersede"] as const) {
    it(`${terminal} clears the pending retry so a stale retry_delay_fired starts nothing`, () => {
      resetIds();
      const d = deps();
      let state = initialTransportOrchestratorState();
      state = {
        ...state,
        plan: {
          allowedKinds: ["webrtc", "websocket"],
          denials: [],
          preference: "auto",
          turnRequired: false,
        },
        parentState: "establishing",
        children: [makeChild("a", "webrtc", "pending", { turnLifecycle: null })],
      };
      // Close the only child (nonterminal) → arms a same-kind retry through the
      // production path (pendingRetry set, retry timer tracked in pendingTimers).
      const closed = transportSelectionReducer(
        state,
        { kind: "child_closed", atMs: 100, childAttemptId: "a", reason: "network_unreachable" },
        d,
      );
      state = closed.state;
      expect(closed.commands.find((c) => c.kind === "schedule_retry")).toBeDefined();
      expect(state.pendingRetry).not.toBeNull();
      expect(state.pendingTimers.some((t) => t.startsWith("retry_"))).toBe(true);
      // Terminate/background → clears the pending retry and cancels its timer.
      const term = transportSelectionReducer(state, { kind: terminal, atMs: 200 }, d);
      state = term.state;
      expect(state.pendingRetry).toBeNull();
      expect(term.commands.some((c) => c.kind === "cancel_timer")).toBe(true);
      // A stale retry_delay_fired must NOT start a child after termination.
      const late = transportSelectionReducer(state, { kind: "retry_delay_fired", atMs: 2000 }, d);
      expect(late.commands.find((c) => c.kind === "start_child")).toBeUndefined();
    });
  }

  // H4 — a failed WebRTC health probe closes the child (so routing can no longer
  // select it) and starts the authorized WebSocket fallback under auto.
  it("a failed WebRTC health probe closes the child and starts authorized WebSocket fallback", () => {
    resetIds();
    const d = deps();
    let state = initialTransportOrchestratorState();
    state = {
      ...state,
      plan: {
        allowedKinds: ["webrtc", "websocket"],
        denials: [],
        preference: "auto",
        turnRequired: false,
      },
      parentState: "active",
      children: [makeChild("a", "webrtc", "active", { consecutiveMisses: 5 })],
    };
    // A sixth consecutive miss reaches the failed threshold.
    const r = transportSelectionReducer(
      state,
      {
        kind: "health_probe",
        atMs: 100,
        sample: {
          kind: "webrtc",
          childAttemptId: "a",
          atMs: 100,
          success: false,
          bufferedBytes: 0,
        },
      },
      d,
    );
    state = r.state;
    const child = state.children.find((c) => c.childAttemptId === "a");
    expect(child?.health).toBe("failed");
    expect(child?.state).toBe("closed");
    // The closed child is no longer routable.
    expect(selectRouteChild(state.children, "interactive")).toBeNull();
    // The authorized WebSocket fallback was started.
    expect(
      r.commands.find(
        (c) =>
          c.kind === "start_child" &&
          (c as { transportKind: string }).transportKind === "websocket",
      ),
    ).toBeDefined();
  });

  // H5 — a WebRTC child closing before its deadline must not suppress the
  // fallback: the deadline decides from aggregate state, not the original child.
  it("a WebRTC child closing before its deadline still yields the WebSocket fallback", () => {
    resetIds();
    const d = deps();
    let now = 0;
    d.now = () => now;
    let state = initialTransportOrchestratorState();
    const plan = transportSelectionReducer(
      state,
      { kind: "plan_requested", atMs: 0, input: fullInput(), trainId: "train_1" },
      d,
    );
    state = plan.state;
    const startCmd = plan.commands.find((c) => c.kind === "start_child") as {
      childAttemptId: string;
    };
    const deadlineCmd = plan.commands.find((c) => c.kind === "schedule_deadline_timer") as {
      timerId: string;
    };
    state = transportSelectionReducer(
      state,
      {
        kind: "child_attempt_reserved",
        atMs: 0,
        childAttemptId: startCmd.childAttemptId,
        transportKind: "webrtc",
        transportEpoch: "ep_1",
        generation: 1,
        reservation: {} as RemoteTransportRetryReservationV1,
      },
      d,
    ).state;
    // The initial WebRTC child closes (nonterminal) BEFORE the deadline.
    state = transportSelectionReducer(
      state,
      {
        kind: "child_closed",
        atMs: 5000,
        childAttemptId: startCmd.childAttemptId,
        reason: "network_unreachable",
      },
      d,
    ).state;
    expect(state.children.find((c) => c.childAttemptId === startCmd.childAttemptId)?.state).toBe(
      "closed",
    );
    // The stale deadline fires; aggregate state has no active WebRTC and no
    // WebSocket, so the authorized WebSocket fallback MUST start.
    now = 10000;
    const fired = transportSelectionReducer(
      state,
      {
        kind: "deadline_timer_fired",
        atMs: now,
        timerId: deadlineCmd.timerId,
        childAttemptId: startCmd.childAttemptId,
      },
      d,
    );
    expect(
      fired.commands.find(
        (c) =>
          c.kind === "start_child" &&
          (c as { transportKind: string }).transportKind === "websocket",
      ),
    ).toBeDefined();
  });
});

// ---------------------------------------------------------------------------
// Cross-language fixtures — the committed JSON is the single source of truth.
// ---------------------------------------------------------------------------

describe("remote_transport_selection_fixture_vocabulary", () => {
  it("matches the exported TS unions for every shared enum", () => {
    expect(vocabulary.transportKinds).toEqual([...REMOTE_TRANSPORT_KINDS]);
    expect(vocabulary.userPreferences).toEqual([...REMOTE_USER_PREFERENCES]);
    expect(vocabulary.parentStates).toEqual([...REMOTE_PARENT_STATES]);
    expect(vocabulary.childStates).toEqual([...REMOTE_ORDINARY_CHILD_STATES]);
    expect(vocabulary.durableLifecycle).toEqual([...REMOTE_TURN_LIFECYCLE]);
    // Compared against the EXPORTED union directly (no hand-written literal that
    // could drift): `ice_disconnected` is now part of REMOTE_REACHABILITY_CLASSES.
    expect(vocabulary.reachabilityClasses).toEqual([...REMOTE_REACHABILITY_CLASSES]);
    expect(vocabulary.secondChildReasons).toEqual([...REMOTE_SECOND_CHILD_REASONS]);
    expect(vocabulary.transportDenials).toEqual([...REMOTE_TRANSPORT_DENIALS]);
  });
  it("models ice_disconnected as degraded-only, excluded from the fallback subset", () => {
    // The full reachability vocabulary carries `ice_disconnected`, but it is NOT
    // a fallback trigger — the fallback subset is the strict complement.
    expect(REMOTE_REACHABILITY_CLASSES).toContain("ice_disconnected");
    expect(REMOTE_REACHABILITY_FALLBACK_CLASSES).not.toContain("ice_disconnected");
    for (const cls of REMOTE_REACHABILITY_FALLBACK_CLASSES) {
      expect(REMOTE_REACHABILITY_CLASSES).toContain(cls);
    }
    expect(REMOTE_REACHABILITY_FALLBACK_CLASSES.length).toBe(
      REMOTE_REACHABILITY_CLASSES.length - 1,
    );
  });
  it("closed denial vocabulary has the new TURN-unavailable variant", () => {
    // The closed set is enforced by the exact fixture-equality assertion above
    // (`vocabulary.transportDenials` === REMOTE_TRANSPORT_DENIALS); any retired
    // kind would fail that equality, so no separate not.toContain guards are
    // needed here.
    expect(vocabulary.transportDenials).toContain("relay_required_turn_unavailable");
  });
  it("carries the canonical consent tri-state and remaining wire enums", () => {
    // Compared against the EXPORTED constants directly (no hand-written literal
    // arrays that could silently drift from the source of truth).
    expect(vocabulary.consentCapabilities).toEqual([...REMOTE_IP_CONSENT_CAPABILITIES]);
    expect(vocabulary.healthTiers).toEqual([...REMOTE_HEALTH_TIERS]);
    expect(vocabulary.routingClasses).toEqual([...REMOTE_ROUTE_LANES]);
    // `failed` is now part of REMOTE_RESERVATION_TERMINAL_OUTCOMES.
    expect(vocabulary.reservationOutcomes).toEqual([...REMOTE_RESERVATION_TERMINAL_OUTCOMES]);
  });
});

describe("remote_transport_selection_fixture_constants", () => {
  it("matches every exported TS policy constant", () => {
    expect(constantsFixture.initialDeadlineSecs).toBe(REMOTE_AUTO_INITIAL_DEADLINE_SECONDS);
    expect(constantsFixture.minDeadlineSecs).toBe(REMOTE_AUTO_INITIAL_DEADLINE_MIN_SECONDS);
    expect(constantsFixture.maxDeadlineSecs).toBe(REMOTE_AUTO_INITIAL_DEADLINE_MAX_SECONDS);
    expect(constantsFixture.livenessProbeIntervalSecs).toBe(REMOTE_WEBRTC_PROBE_INTERVAL_SECONDS);
    expect(constantsFixture.iceDisconnectedFallbackMisses).toBe(
      REMOTE_WEBRTC_DISCONNECTED_FAIL_PROBES,
    );
    expect(constantsFixture.webrtcHealthyConsecutiveSuccesses).toBe(
      REMOTE_WEBRTC_HEALTHY_SUCCESS_PROBES,
    );
    expect(constantsFixture.webrtcDegradedMisses).toBe(REMOTE_WEBRTC_DEGRADED_MISS_PROBES);
    expect(constantsFixture.webrtcDegradedBufferBytes).toBe(REMOTE_WEBRTC_DEGRADED_BUFFER_BYTES);
    expect(constantsFixture.webrtcFailedMisses).toBe(REMOTE_WEBRTC_FAILED_MISS_PROBES);
    expect(constantsFixture.websocketDegradedUnackedAgeSecs).toBe(
      REMOTE_WEBSOCKET_DEGRADED_OLDEST_UNACKED_SECONDS,
    );
    expect(constantsFixture.websocketDegradedBufferBytes).toBe(
      REMOTE_WEBSOCKET_DEGRADED_BUFFER_BYTES,
    );
    expect(constantsFixture.websocketFailedRetransmissions).toBe(
      REMOTE_WEBSOCKET_FAILED_RETRANSMISSION,
    );
    expect(constantsFixture.recoveryConsecutiveHealthy).toBe(REMOTE_HEALTH_RECOVERY_INTERVALS);
    expect(constantsFixture.drainingTimeoutSecs).toBe(REMOTE_TURN_DRAIN_MAX_SECONDS);
    expect(constantsFixture.maxRoutedCurrentChildren).toBe(
      REMOTE_MAX_CURRENT_WEBRTC + REMOTE_MAX_CURRENT_WEBSOCKET,
    );
    expect(constantsFixture.maxOrdinaryPendingChildren).toBe(REMOTE_MAX_PENDING_CHILDREN_TOTAL);
    expect(constantsFixture.maxPendingPerKind).toBe(REMOTE_MAX_PENDING_CHILDREN_PER_KIND);
    expect(constantsFixture.maxPhysicalChildrenTurnException).toBe(
      REMOTE_MAX_PHYSICAL_CHILDREN_TURN_REPLACEMENT,
    );
    expect(constantsFixture.maxReservationsPerTrain).toBe(REMOTE_RETRY_BUDGET_MAX_PER_TRAIN);
    expect(constantsFixture.maxCommittedReservationsRolling).toBe(REMOTE_RETRY_BUDGET_MAX_PER_HOUR);
    expect(constantsFixture.rollingWindowSecs).toBe(REMOTE_RETRY_BUDGET_WINDOW_SECONDS);
    expect(constantsFixture.retryDelaySecs).toBe(REMOTE_RETRY_DELAY_MS / 1000);
    expect(constantsFixture.maxSameKindRetries).toBe(REMOTE_MAX_RETRIES_PER_KIND);
    expect(constantsFixture.trainIdBytes).toBe(REMOTE_TRAIN_ID_BYTES);
  });
});

describe("remote_transport_selection_fixture_plan_matrix", () => {
  it("replays every vector through the production computeAuthorizedPlan", () => {
    expect(planMatrix.rows.length).toBeGreaterThan(0);
    for (const row of planMatrix.rows) {
      const plan = computeAuthorizedPlan(planInputFromRow(row));
      expect(plan.allowedKinds, row.name).toEqual([...row.expected.allowed_kinds]);
      expect(plan.denials, row.name).toEqual([...row.expected.denials]);
      expect(plan.preference, row.name).toBe(row.expected.preference);
      expect(plan.turnRequired, row.name).toBe(row.expected.turn_required);
    }
  });
  it("every denial in the matrix is a closed-vocabulary kind", () => {
    for (const row of planMatrix.rows) {
      for (const denial of row.expected.denials) {
        expect(REMOTE_TRANSPORT_DENIALS).toContain(denial);
      }
    }
  });
});

// ---------------------------------------------------------------------------
// H7: strict ordered action-stream oracle.
//
// The trace replay asserts the COMPLETE, ORDERED action stream of every fixture
// entry — same length, same order, same fields — not a loose `find()` subset, so
// an extra, missing, or misparametrised emitted command now fails the replay.
// Each TS command is normalised to the canonical Rust `GoldenTraceAction` schema
// and compared element-by-element (child ids resolved through `childMap`, kinds,
// timer seconds, denials, and route targets). Two DOCUMENTED allowlists bridge
// the reducers' genuinely different action vocabularies — never a silent drop.
// ---------------------------------------------------------------------------

// TS-only adapter commands with no canonical Rust `reduce()` action — filtered
// from the normalised TS stream:
//   - cancel_timer / schedule_liveness_probe: adapter timer plumbing the Rust
//     reducer tracks in state, not as emitted actions.
//   - record_ledger_mutation: the operation-ledger side channel Rust integrates
//     by interface only.
//   - begin_turn_replacement / commit_connection_lease: the TS decomposition of
//     the TURN cutover lease handshake that Rust folds into `emit_cutover_lease`
//     (asserted here via child turnLifecycle state).
//   - failover_resend: a resend helper with no reduce() action.
//   - close_child: emitted from DIFFERENT events per language (Rust
//     `reduce_second_lease` / probe-close vs TS inbound `child_closed` / probe),
//     so it is modelled as the child's `closed` state on BOTH sides and asserted
//     via child state, not as an ordered command.
const TS_ONLY_ADAPTER_COMMANDS: ReadonlySet<string> = new Set([
  "cancel_timer",
  "schedule_liveness_probe",
  "record_ledger_mutation",
  "begin_turn_replacement",
  "commit_connection_lease",
  "failover_resend",
  "close_child",
]);

// Canonical Rust actions the TS reducer models as STATE (not emitted commands) —
// filtered from the expected stream:
//   - parent_transition: asserted separately via `parent_state_after`.
//   - inert: a no-op marker; the TS reducer emits no command for it.
//   - emit_cutover_lease: asserted via child turnLifecycle (current/draining).
//   - close_child: see above — asserted via the child's `closed` state.
const RUST_STATE_MODELLED_ACTIONS: ReadonlySet<string> = new Set([
  "parent_transition",
  "inert",
  "emit_cutover_lease",
  "close_child",
]);

interface NormalizedAction {
  readonly kind: string;
  readonly transportKind?: string;
  readonly secs?: number;
  readonly denial?: string;
  readonly deliveryId?: string;
  readonly tsChild?: string;
}

/** Normalise a TS command to the canonical Rust action schema, or null when it
 *  is a documented TS-only adapter command. Throws on any unrecognised kind so a
 *  new command can never be silently dropped. */
function normalizeTsCommand(cmd: RemoteTransportCommand): NormalizedAction | null {
  switch (cmd.kind) {
    case "start_child":
      return {
        kind: cmd.reservationType === "replacement" ? "start_replacement_pending" : "start_child",
        transportKind: cmd.transportKind,
        tsChild: cmd.childAttemptId,
      };
    case "schedule_deadline_timer":
      return { kind: "arm_deadline_timer", secs: cmd.deadlineSeconds };
    case "schedule_retry":
      return { kind: "arm_retry_delay", secs: cmd.delayMs / 1000 };
    case "route_delivery":
      return { kind: "route_delivery", deliveryId: cmd.deliveryId, tsChild: cmd.childAttemptId };
    case "deny":
      return { kind: "deny", denial: cmd.denials[0] };
    default:
      if (TS_ONLY_ADAPTER_COMMANDS.has(cmd.kind)) return null;
      throw new Error(`H7: unhandled TS command kind "${cmd.kind}" in trace normalization`);
  }
}

/** Resolve a Rust child-attempt integer to its TS id, asserting the entry exists.
 *  The reducer always populates `childMap` for a child before the trace drives an
 *  event referencing it, so a missing entry is a test-harness bug, not `undefined`. */
function childId(map: Record<number, string>, n: number): string {
  const id = map[n];
  if (id === undefined) {
    throw new Error(`childMap has no entry for child ${n}`);
  }
  return id;
}

/** Assert the emitted TS command stream equals the fixture entry's action stream
 *  as an ordered list (after both documented filters), binding Rust child ints to
 *  TS ids on start actions and resolving route targets through `childMap`. */
function assertActionStream(
  where: string,
  commands: readonly RemoteTransportCommand[],
  entry: TraceEntry,
  childMap: Record<number, string>,
): void {
  const emitted: NormalizedAction[] = [];
  for (const cmd of commands) {
    const norm = normalizeTsCommand(cmd);
    if (norm !== null) emitted.push(norm);
  }
  const expected = entry.actions.filter((a) => !RUST_STATE_MODELLED_ACTIONS.has(a.kind));
  expect(emitted.length, `${where} action count`).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    const exp = expected[i]!;
    const got = emitted[i]!;
    expect(got.kind, `${where} action[${i}] kind`).toBe(exp.kind);
    switch (exp.kind) {
      case "start_child":
      case "start_replacement_pending":
        expect(got.transportKind, `${where} action[${i}] transport_kind`).toBe(exp.transport_kind);
        // A start action introduces a new child; bind the Rust int to the
        // TS-generated id for later reference-action resolution.
        childMap[Number(exp.child_attempt)] = got.tsChild as string;
        break;
      case "arm_deadline_timer":
      case "arm_retry_delay":
        expect(got.secs, `${where} action[${i}] secs`).toBe(exp.secs);
        break;
      case "deny":
        expect(got.denial, `${where} action[${i}] denial`).toBe(exp.denial);
        break;
      case "route_delivery":
        expect(got.deliveryId, `${where} action[${i}] delivery_id`).toBe(exp.delivery_id);
        expect(got.tsChild, `${where} action[${i}] route target`).toBe(
          childMap[Number(exp.child_attempt)],
        );
        break;
      default:
        throw new Error(`${where}: unhandled expected action kind "${exp.kind}"`);
    }
  }
}

describe("remote_transport_selection_fixture_traces", () => {
  function scenarioByName(name: string) {
    const scenario = traces.scenarios.find((s) => s.name === name);
    expect(scenario, `scenario ${name} present in traces.json`).toBeDefined();
    return scenario as { name: string; trace: readonly TraceEntry[] };
  }

  const RESERVATION = {} as RemoteTransportRetryReservationV1;

  // Supplementary guard: every recorded step uses the closed shared vocabulary.
  // The five behavioral replays below are the substantive per-scenario checks.
  it("every recorded step uses the closed shared vocabulary", () => {
    expect(traces.scenarios.map((s) => s.name)).toEqual([
      "auto_deadline_fallback",
      "preference_forced_denial",
      "turn_replacement_cutover",
      "retry_budget_exhaustion",
      "multi_path_routing",
    ]);
    for (const scenario of traces.scenarios) {
      expect(scenario.trace.length).toBeGreaterThan(0);
      for (const entry of scenario.trace) {
        expect(REMOTE_PARENT_STATES).toContain(entry.parent_state_before);
        expect(REMOTE_PARENT_STATES).toContain(entry.parent_state_after);
        for (const action of entry.actions) {
          if (action.kind === "deny" && action.denial !== undefined) {
            expect(REMOTE_TRANSPORT_DENIALS).toContain(action.denial);
          }
        }
      }
    }
  });

  // Replay a scenario's recorded input sequence through the production
  // `transportSelectionReducer`, translating each canonical Rust trace input
  // onto the TS reducer's (now-aligned) event vocabulary. Rust child-attempt
  // integers are bound to the TS-generated ids as the reducer emits start
  // commands. For EVERY entry both (a) the resulting parent state is asserted
  // against `entry.parent_state_after` and (b) the COMPLETE ORDERED command
  // stream is asserted against `entry.actions` via `assertActionStream` (same
  // length, same order, same fields — an extra/missing/misparametrised action
  // now fails). The translator is EXHAUSTIVE — an unrecognised input kind throws,
  // so a fixture entry can never be silently skipped. All FIVE scenarios run
  // through this one loop; there is no bespoke hand-written sequence.
  function runTrace(name: string, planInput: RemoteTransportPlanInput) {
    const scenario = scenarioByName(name);
    resetIds();
    const d = deps();
    d.now = () => 0;
    let state = initialTransportOrchestratorState();
    const childMap: Record<number, string> = {};
    const ctx = { deadlineTimerId: "", webrtcChild: "" };

    const reserve = (childAttemptId: string, kind: RemoteTransportKind, generation: number) => {
      state = transportSelectionReducer(
        state,
        {
          kind: "child_attempt_reserved",
          atMs: 0,
          childAttemptId,
          transportKind: kind,
          transportEpoch: `ep_${childAttemptId}`,
          generation,
          reservation: RESERVATION,
        },
        d,
      ).state;
    };
    const startChildCommand = (commands: readonly RemoteTransportCommand[], kind?: string) =>
      commands.find(
        (c) =>
          c.kind === "start_child" &&
          (kind === undefined || (c as { transportKind: string }).transportKind === kind),
      ) as { childAttemptId: string; transportKind: RemoteTransportKind } | undefined;

    for (const entry of scenario.trace) {
      const input = entry.input;
      const where = `${name} step ${entry.step} (${input.kind})`;
      const assertParent = () =>
        expect(state.parentState, `${where} parent_state_after`).toBe(entry.parent_state_after);

      switch (input.kind) {
        case "start_plan": {
          const r = transportSelectionReducer(
            state,
            { kind: "plan_requested", atMs: 0, input: planInput, trainId: "train_1" },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          const sc = startChildCommand(r.commands);
          if (sc) {
            const deadlineCmd = r.commands.find((c) => c.kind === "schedule_deadline_timer") as
              | { timerId: string }
              | undefined;
            ctx.deadlineTimerId = deadlineCmd?.timerId ?? "";
            ctx.webrtcChild = sc.childAttemptId;
            reserve(sc.childAttemptId, sc.transportKind, 1);
          }
          break;
        }
        case "child_active": {
          // A `child_active` for a not-yet-created child is a recorded inert step
          // in Rust; drive it with the mapped id (or a sentinel that matches no
          // child) and assert the (empty) stream and transition regardless.
          const id = childMap[Number(input.child_attempt)] ?? "__unmapped__";
          const r = transportSelectionReducer(
            state,
            { kind: "child_active", atMs: Number(input.now_ms), childAttemptId: id },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          break;
        }
        case "deadline_fired": {
          const r = transportSelectionReducer(
            state,
            {
              kind: "deadline_timer_fired",
              atMs: Number(input.now_ms),
              timerId: ctx.deadlineTimerId,
              childAttemptId: ctx.webrtcChild,
            },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          const wsStart = startChildCommand(r.commands, "websocket");
          if (wsStart) reserve(wsStart.childAttemptId, "websocket", 1);
          break;
        }
        case "child_closed": {
          const id = childMap[Number(input.child_attempt)] ?? "__unmapped__";
          const securityFailure = Boolean(input.security_failure);
          const r = transportSelectionReducer(
            state,
            {
              kind: "child_closed",
              atMs: 0,
              childAttemptId: id,
              // security_failure → a terminal reason; otherwise a reachability
              // reason that arms the canonical same-kind retry.
              reason: securityFailure ? "auth_failure" : "network_unreachable",
            },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          if (id !== "__unmapped__") {
            expect(state.children.find((c) => c.childAttemptId === id)?.state).toBe("closed");
          }
          break;
        }
        case "retry_delay_fired": {
          const r = transportSelectionReducer(
            state,
            { kind: "retry_delay_fired", atMs: Number(input.now_ms) },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          const sc = startChildCommand(r.commands);
          if (sc) reserve(sc.childAttemptId, sc.transportKind, 2);
          break;
        }
        case "request_second_child": {
          const r = transportSelectionReducer(
            state,
            {
              kind: "second_child_requested",
              atMs: Number(input.now_ms),
              reason: input.reason as RemoteSecondChildReason,
              childAttemptId: childId(childMap, 1),
              transportEpoch: "ep_sc",
            },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          const sc = startChildCommand(r.commands);
          if (sc) reserve(sc.childAttemptId, sc.transportKind, 1);
          break;
        }
        case "credential_rotation_lead": {
          // Drive the DEDICATED `credential_rotation_lead` event (mirrors the
          // Rust `reduce_credential_rotation`) — NOT `second_child_requested`.
          const r = transportSelectionReducer(
            state,
            { kind: "credential_rotation_lead", atMs: Number(input.now_ms) },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          const sc = startChildCommand(r.commands);
          if (sc) reserve(sc.childAttemptId, "webrtc", 2);
          break;
        }
        case "supervisor_cutover_ack": {
          const oldId = childId(childMap, Number(input.old));
          const newId = childId(childMap, Number(input.new));
          // The daemon commits the connection lease out-of-band before the
          // supervisor acks it; represent that committed lease in state, then
          // drive the production `lease_supervisor_acked` cutover path.
          const leaseId = "lease_cutover";
          state = { ...state, activeLease: buildConnectionLease(leaseId, [newId], [oldId]) };
          const r = transportSelectionReducer(
            state,
            {
              kind: "lease_supervisor_acked",
              atMs: 0,
              leaseId,
              currentChildAttemptIds: [newId],
              drainingChildAttemptIds: [oldId],
            },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          // `emit_cutover_lease` is modelled via state (documented allowlist):
          // assert the recorded lease targets map to the cutover children and the
          // resulting turnLifecycle transition.
          const act = entry.actions.find((a) => a.kind === "emit_cutover_lease");
          expect(act, `${where} emit_cutover_lease recorded`).toBeDefined();
          expect(childMap[Number(act!.current)], `${where} cutover current target`).toBe(newId);
          expect(childMap[Number(act!.draining)], `${where} cutover draining target`).toBe(oldId);
          expect(state.children.find((c) => c.childAttemptId === oldId)?.turnLifecycle).toBe(
            "draining",
          );
          expect(state.children.find((c) => c.childAttemptId === newId)?.turnLifecycle).toBe(
            "current",
          );
          break;
        }
        case "second_lease": {
          const oldId = childId(childMap, Number(input.old));
          const r = transportSelectionReducer(
            state,
            { kind: "child_closed", atMs: 0, childAttemptId: oldId, reason: "local_close" },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          // `close_child` is modelled via state (documented allowlist): assert the
          // recorded close target maps to the drained child, now `closed`.
          const act = entry.actions.find((a) => a.kind === "close_child");
          expect(act, `${where} close_child recorded`).toBeDefined();
          expect(childMap[Number(act!.child_attempt)], `${where} close target`).toBe(oldId);
          expect(state.children.find((c) => c.childAttemptId === oldId)?.state).toBe("closed");
          break;
        }
        case "webrtc_probe": {
          const id = childMap[Number(input.child_attempt)] ?? "__unmapped__";
          const r = transportSelectionReducer(
            state,
            {
              kind: "health_probe",
              atMs: 0,
              sample: {
                kind: "webrtc",
                childAttemptId: id,
                atMs: 0,
                success: Boolean(input.success),
                bufferedBytes: Number(input.buffered_bytes),
              },
            },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          break;
        }
        case "websocket_ack_progress": {
          const id = childMap[Number(input.child_attempt)] ?? "__unmapped__";
          const r = transportSelectionReducer(
            state,
            {
              kind: "health_probe",
              atMs: 0,
              sample: {
                kind: "websocket",
                childAttemptId: id,
                atMs: 0,
                oldestUnackedAgeSeconds: Number(input.oldest_unacked_age_secs),
                bufferedBytes: Number(input.buffered_bytes),
                retransmissionCount: Number(input.retransmissions),
              },
            },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          break;
        }
        case "route_request": {
          const r = transportSelectionReducer(
            state,
            {
              kind: "route_request",
              atMs: 0,
              deliveryId: String(input.delivery_id),
              lane: input.routing_class as RemoteRouteLane,
              payloadBytes: 64,
            },
            d,
          );
          state = r.state;
          assertParent();
          assertActionStream(where, r.commands, entry, childMap);
          break;
        }
        default:
          throw new Error(
            `exhaustive trace translator: unhandled canonical input "${input.kind}" in ${name}`,
          );
      }
    }
    return { state, childMap };
  }

  it("auto_deadline_fallback replays through the production reducer", () => {
    runTrace("auto_deadline_fallback", fullInput());
  });

  it("preference_forced_denial replays a webrtc-unauthorized denial through the reducer", () => {
    runTrace(
      "preference_forced_denial",
      fullInput({
        userPreference: "webrtc",
        deploymentWebrtc: false,
        serviceWebrtc: false,
        tenantWebrtc: false,
        daemonWebrtc: false,
      }),
    );
  });

  it("turn_replacement_cutover replays replacement, cutover, and second-lease close", () => {
    const { state, childMap } = runTrace("turn_replacement_cutover", fullInput());
    // The old child is drained-then-closed; the replacement is the new current.
    expect(state.children.find((c) => c.childAttemptId === childMap[1])?.state).toBe("closed");
    expect(state.children.find((c) => c.childAttemptId === childMap[2])?.turnLifecycle).toBe(
      "current",
    );
  });

  it("multi_path_routing replays two deliveries across two active children", () => {
    const { state, childMap } = runTrace("multi_path_routing", fullInput());
    // AC 8 invariants: both deliveries entered the ledger, and closing one child
    // leaves the other intact.
    expect(state.ledgerDeliveries.size).toBe(2);
    const other = childId(childMap, 2);
    const afterClose = transportSelectionReducer(
      state,
      {
        kind: "child_closed",
        atMs: 999,
        childAttemptId: childId(childMap, 1),
        reason: "local_close",
      },
      deps(),
    ).state;
    expect(afterClose.children.find((c) => c.childAttemptId === other)?.state).toBe("active");
  });

  it("retry_budget_exhaustion replays the child_closed-driven retry through the reducer", () => {
    // The canonical scenario is replayed ENTRY-BY-ENTRY through the shared
    // translator (no bespoke sequence): `start_plan` → `child_closed` (arms the
    // same-kind retry) → `retry_delay_fired` (starts it) → `child_closed`
    // (budget exhausted → terminal failure). `runTrace` asserts every recorded
    // parent transition and action; here we confirm the terminal state.
    const { state } = runTrace("retry_budget_exhaustion", fullInput());
    expect(state.parentState, "retry budget exhausted → terminal failure").toBe("failed");
  });
});

// ---------------------------------------------------------------------------
// Raw-byte fixture guard — a formatting-only mutation of a committed fixture
// (reindentation, added/removed whitespace, lost trailing newline) is caught on
// the TS side too, not only by the Rust byte assertion. The canonical renderer
// below mirrors the in-crate Rust `render_json` (two-space indent, single-line
// arrays that fit in 100 columns, one trailing newline) and preserves the
// committed key order, so re-rendering the parsed file must reproduce the file
// byte-for-byte when it is in canonical form.
// ---------------------------------------------------------------------------

const CANONICAL_LINE_WIDTH = 100;

function canonicalScalar(value: unknown): string {
  return JSON.stringify(value);
}

function renderCanonicalValue(value: unknown, indent: number, out: string[]): void {
  if (Array.isArray(value)) {
    renderCanonicalArray(value, indent, out);
  } else if (value !== null && typeof value === "object") {
    renderCanonicalObject(value as Record<string, unknown>, indent, out);
  } else {
    out.push(canonicalScalar(value));
  }
}

function renderCanonicalObject(map: Record<string, unknown>, indent: number, out: string[]): void {
  const keys = Object.keys(map);
  if (keys.length === 0) {
    out.push("{}");
    return;
  }
  out.push("{\n");
  const inner = indent + 2;
  keys.forEach((key, i) => {
    out.push(" ".repeat(inner));
    out.push(canonicalScalar(key));
    out.push(": ");
    renderCanonicalValue(map[key], inner, out);
    if (i + 1 < keys.length) out.push(",");
    out.push("\n");
  });
  out.push(" ".repeat(indent));
  out.push("}");
}

function renderCanonicalArray(items: readonly unknown[], indent: number, out: string[]): void {
  if (items.length === 0) {
    out.push("[]");
    return;
  }
  const composite = items.some(
    (item) => Array.isArray(item) || (item !== null && typeof item === "object"),
  );
  if (!composite) {
    const single = `[${items.map(canonicalScalar).join(", ")}]`;
    if (indent + single.length <= CANONICAL_LINE_WIDTH) {
      out.push(single);
      return;
    }
  }
  out.push("[\n");
  const inner = indent + 2;
  items.forEach((item, i) => {
    out.push(" ".repeat(inner));
    renderCanonicalValue(item, inner, out);
    if (i + 1 < items.length) out.push(",");
    out.push("\n");
  });
  out.push(" ".repeat(indent));
  out.push("]");
}

function renderCanonicalJson(value: unknown): string {
  const out: string[] = [];
  renderCanonicalValue(value, 0, out);
  out.push("\n");
  return out.join("");
}

describe("remote_transport_selection_fixture_bytes", () => {
  const fixtureFiles = [
    "vocabulary.json",
    "constants.json",
    "plan-matrix.json",
    "traces.json",
  ] as const;

  for (const file of fixtureFiles) {
    it(`${file} is in canonical byte form`, () => {
      const raw = readFileSync(
        fileURLToPath(new URL(`../fixtures/remote-transport-selection/${file}`, import.meta.url)),
        "utf8",
      );
      // No CRLF, no tabs, and exactly one trailing newline.
      expect(raw.includes("\r"), `${file} must not contain CR`).toBe(false);
      expect(raw.includes("\t"), `${file} must not contain tabs`).toBe(false);
      expect(raw.endsWith("\n"), `${file} must end with a newline`).toBe(true);
      // Re-rendering the parsed content reproduces the committed bytes exactly:
      // a reindent or whitespace edit changes `raw` but not `renderCanonicalJson`.
      expect(raw).toBe(renderCanonicalJson(JSON.parse(raw)));
    });
  }
});
