/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangSignupRouteImport } from './routes/$lang/signup'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangDeviceRouteImport } from './routes/$lang/device'
import { Route as LangCookiePolicyRouteImport } from './routes/$lang/cookie-policy'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangAuthRouteImport } from './routes/$lang/_auth'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as LangVideosVideoIdRouteImport } from './routes/$lang/videos.$videoId'
import { Route as LangAdminVideosRouteImport } from './routes/$lang/admin/videos'
import { Route as LangAdminUsersRouteImport } from './routes/$lang/admin/users'
import { Route as LangAdminSettingsRouteImport } from './routes/$lang/admin/settings'
import { Route as LangAdminSeedRouteImport } from './routes/$lang/admin/seed'
import { Route as LangAdminJobsRouteImport } from './routes/$lang/admin/jobs'
import { Route as LangAdminEnterpriseRouteImport } from './routes/$lang/admin/enterprise'
import { Route as LangAdminDevicesRouteImport } from './routes/$lang/admin/devices'
import { Route as LangAdminAssetsRouteImport } from './routes/$lang/admin/assets'
import { Route as LangAdminApiKeysRouteImport } from './routes/$lang/admin/api-keys'
import { Route as LangAuthSettingsRouteImport } from './routes/$lang/_auth/settings'
import { Route as LangAuthInstancesRouteImport } from './routes/$lang/_auth/instances'
import { Route as LangAuthDashboardRouteImport } from './routes/$lang/_auth/dashboard'
import { Route as LangAdminVideosIndexRouteImport } from './routes/$lang/admin/videos/index'
import { Route as LangAdminAssetsIndexRouteImport } from './routes/$lang/admin/assets/index'
import { Route as LangAuthSettingsIndexRouteImport } from './routes/$lang/_auth/settings/index'
import { Route as LangAdminVideosVideoIdRouteImport } from './routes/$lang/admin/videos/$videoId'
import { Route as LangAdminAssetsCleanupRouteImport } from './routes/$lang/admin/assets/cleanup'
import { Route as LangAuthSettingsSecurityRouteImport } from './routes/$lang/_auth/settings/security'
import { Route as LangAuthSettingsPrivacyRouteImport } from './routes/$lang/_auth/settings/privacy'
import { Route as LangAuthInstancesInstanceIdRouteImport } from './routes/$lang/_auth/instances.$instanceId'
import { Route as LangAuthInstancesInstanceIdTerminalRouteImport } from './routes/$lang/_auth/instances.$instanceId.terminal'
import { Route as LangAuthInstancesInstanceIdSharingRouteImport } from './routes/$lang/_auth/instances.$instanceId.sharing'
import { Route as LangAuthInstancesInstanceIdProjectsProjectIdRouteImport } from './routes/$lang/_auth/instances.$instanceId.projects.$projectId'
import { Route as LangAuthInstancesInstanceIdProjectsProjectIdFilesRouteImport } from './routes/$lang/_auth/instances.$instanceId.projects.$projectId.files'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangSignupRoute = LangSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangDeviceRoute = LangDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => LangRoute,
} as any)
const LangCookiePolicyRoute = LangCookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangVideosVideoIdRoute = LangVideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminVideosRoute = LangAdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminUsersRoute = LangAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminSettingsRoute = LangAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminSeedRoute = LangAdminSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminJobsRoute = LangAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminEnterpriseRoute = LangAdminEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminDevicesRoute = LangAdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminAssetsRoute = LangAdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminApiKeysRoute = LangAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAuthSettingsRoute = LangAuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAuthInstancesRoute = LangAuthInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAuthDashboardRoute = LangAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangAuthRoute,
} as any)
const LangAdminVideosIndexRoute = LangAdminVideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminVideosRoute,
} as any)
const LangAdminAssetsIndexRoute = LangAdminAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminAssetsRoute,
} as any)
const LangAuthSettingsIndexRoute = LangAuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAuthSettingsRoute,
} as any)
const LangAdminVideosVideoIdRoute = LangAdminVideosVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => LangAdminVideosRoute,
} as any)
const LangAdminAssetsCleanupRoute = LangAdminAssetsCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => LangAdminAssetsRoute,
} as any)
const LangAuthSettingsSecurityRoute =
  LangAuthSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LangAuthSettingsRoute,
  } as any)
const LangAuthSettingsPrivacyRoute = LangAuthSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangAuthSettingsRoute,
} as any)
const LangAuthInstancesInstanceIdRoute =
  LangAuthInstancesInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => LangAuthInstancesRoute,
  } as any)
const LangAuthInstancesInstanceIdTerminalRoute =
  LangAuthInstancesInstanceIdTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => LangAuthInstancesInstanceIdRoute,
  } as any)
const LangAuthInstancesInstanceIdSharingRoute =
  LangAuthInstancesInstanceIdSharingRouteImport.update({
    id: '/sharing',
    path: '/sharing',
    getParentRoute: () => LangAuthInstancesInstanceIdRoute,
  } as any)
const LangAuthInstancesInstanceIdProjectsProjectIdRoute =
  LangAuthInstancesInstanceIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => LangAuthInstancesInstanceIdRoute,
  } as any)
const LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute =
  LangAuthInstancesInstanceIdProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => LangAuthInstancesInstanceIdProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/cookie-policy': typeof LangCookiePolicyRoute
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dashboard': typeof LangAuthDashboardRoute
  '/$lang/instances': typeof LangAuthInstancesRouteWithChildren
  '/$lang/settings': typeof LangAuthSettingsRouteWithChildren
  '/$lang/admin/api-keys': typeof LangAdminApiKeysRoute
  '/$lang/admin/assets': typeof LangAdminAssetsRouteWithChildren
  '/$lang/admin/devices': typeof LangAdminDevicesRoute
  '/$lang/admin/enterprise': typeof LangAdminEnterpriseRoute
  '/$lang/admin/jobs': typeof LangAdminJobsRoute
  '/$lang/admin/seed': typeof LangAdminSeedRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin/videos': typeof LangAdminVideosRouteWithChildren
  '/$lang/videos/$videoId': typeof LangVideosVideoIdRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/instances/$instanceId': typeof LangAuthInstancesInstanceIdRouteWithChildren
  '/$lang/settings/privacy': typeof LangAuthSettingsPrivacyRoute
  '/$lang/settings/security': typeof LangAuthSettingsSecurityRoute
  '/$lang/admin/assets/cleanup': typeof LangAdminAssetsCleanupRoute
  '/$lang/admin/videos/$videoId': typeof LangAdminVideosVideoIdRoute
  '/$lang/settings/': typeof LangAuthSettingsIndexRoute
  '/$lang/admin/assets/': typeof LangAdminAssetsIndexRoute
  '/$lang/admin/videos/': typeof LangAdminVideosIndexRoute
  '/$lang/instances/$instanceId/sharing': typeof LangAuthInstancesInstanceIdSharingRoute
  '/$lang/instances/$instanceId/terminal': typeof LangAuthInstancesInstanceIdTerminalRoute
  '/$lang/instances/$instanceId/projects/$projectId': typeof LangAuthInstancesInstanceIdProjectsProjectIdRouteWithChildren
  '/$lang/instances/$instanceId/projects/$projectId/files': typeof LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/cookie-policy': typeof LangCookiePolicyRoute
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/dashboard': typeof LangAuthDashboardRoute
  '/$lang/instances': typeof LangAuthInstancesRouteWithChildren
  '/$lang/admin/api-keys': typeof LangAdminApiKeysRoute
  '/$lang/admin/devices': typeof LangAdminDevicesRoute
  '/$lang/admin/enterprise': typeof LangAdminEnterpriseRoute
  '/$lang/admin/jobs': typeof LangAdminJobsRoute
  '/$lang/admin/seed': typeof LangAdminSeedRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/videos/$videoId': typeof LangVideosVideoIdRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/instances/$instanceId': typeof LangAuthInstancesInstanceIdRouteWithChildren
  '/$lang/settings/privacy': typeof LangAuthSettingsPrivacyRoute
  '/$lang/settings/security': typeof LangAuthSettingsSecurityRoute
  '/$lang/admin/assets/cleanup': typeof LangAdminAssetsCleanupRoute
  '/$lang/admin/videos/$videoId': typeof LangAdminVideosVideoIdRoute
  '/$lang/settings': typeof LangAuthSettingsIndexRoute
  '/$lang/admin/assets': typeof LangAdminAssetsIndexRoute
  '/$lang/admin/videos': typeof LangAdminVideosIndexRoute
  '/$lang/instances/$instanceId/sharing': typeof LangAuthInstancesInstanceIdSharingRoute
  '/$lang/instances/$instanceId/terminal': typeof LangAuthInstancesInstanceIdTerminalRoute
  '/$lang/instances/$instanceId/projects/$projectId': typeof LangAuthInstancesInstanceIdProjectsProjectIdRouteWithChildren
  '/$lang/instances/$instanceId/projects/$projectId/files': typeof LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_auth': typeof LangAuthRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/cookie-policy': typeof LangCookiePolicyRoute
  '/$lang/device': typeof LangDeviceRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_auth/dashboard': typeof LangAuthDashboardRoute
  '/$lang/_auth/instances': typeof LangAuthInstancesRouteWithChildren
  '/$lang/_auth/settings': typeof LangAuthSettingsRouteWithChildren
  '/$lang/admin/api-keys': typeof LangAdminApiKeysRoute
  '/$lang/admin/assets': typeof LangAdminAssetsRouteWithChildren
  '/$lang/admin/devices': typeof LangAdminDevicesRoute
  '/$lang/admin/enterprise': typeof LangAdminEnterpriseRoute
  '/$lang/admin/jobs': typeof LangAdminJobsRoute
  '/$lang/admin/seed': typeof LangAdminSeedRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/admin/videos': typeof LangAdminVideosRouteWithChildren
  '/$lang/videos/$videoId': typeof LangVideosVideoIdRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/_auth/instances/$instanceId': typeof LangAuthInstancesInstanceIdRouteWithChildren
  '/$lang/_auth/settings/privacy': typeof LangAuthSettingsPrivacyRoute
  '/$lang/_auth/settings/security': typeof LangAuthSettingsSecurityRoute
  '/$lang/admin/assets/cleanup': typeof LangAdminAssetsCleanupRoute
  '/$lang/admin/videos/$videoId': typeof LangAdminVideosVideoIdRoute
  '/$lang/_auth/settings/': typeof LangAuthSettingsIndexRoute
  '/$lang/admin/assets/': typeof LangAdminAssetsIndexRoute
  '/$lang/admin/videos/': typeof LangAdminVideosIndexRoute
  '/$lang/_auth/instances/$instanceId/sharing': typeof LangAuthInstancesInstanceIdSharingRoute
  '/$lang/_auth/instances/$instanceId/terminal': typeof LangAuthInstancesInstanceIdTerminalRoute
  '/$lang/_auth/instances/$instanceId/projects/$projectId': typeof LangAuthInstancesInstanceIdProjectsProjectIdRouteWithChildren
  '/$lang/_auth/instances/$instanceId/projects/$projectId/files': typeof LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/admin'
    | '/$lang/cookie-policy'
    | '/$lang/device'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/'
    | '/$lang/dashboard'
    | '/$lang/instances'
    | '/$lang/settings'
    | '/$lang/admin/api-keys'
    | '/$lang/admin/assets'
    | '/$lang/admin/devices'
    | '/$lang/admin/enterprise'
    | '/$lang/admin/jobs'
    | '/$lang/admin/seed'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin/videos'
    | '/$lang/videos/$videoId'
    | '/$lang/admin/'
    | '/$lang/instances/$instanceId'
    | '/$lang/settings/privacy'
    | '/$lang/settings/security'
    | '/$lang/admin/assets/cleanup'
    | '/$lang/admin/videos/$videoId'
    | '/$lang/settings/'
    | '/$lang/admin/assets/'
    | '/$lang/admin/videos/'
    | '/$lang/instances/$instanceId/sharing'
    | '/$lang/instances/$instanceId/terminal'
    | '/$lang/instances/$instanceId/projects/$projectId'
    | '/$lang/instances/$instanceId/projects/$projectId/files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/cookie-policy'
    | '/$lang/device'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/dashboard'
    | '/$lang/instances'
    | '/$lang/admin/api-keys'
    | '/$lang/admin/devices'
    | '/$lang/admin/enterprise'
    | '/$lang/admin/jobs'
    | '/$lang/admin/seed'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/videos/$videoId'
    | '/$lang/admin'
    | '/$lang/instances/$instanceId'
    | '/$lang/settings/privacy'
    | '/$lang/settings/security'
    | '/$lang/admin/assets/cleanup'
    | '/$lang/admin/videos/$videoId'
    | '/$lang/settings'
    | '/$lang/admin/assets'
    | '/$lang/admin/videos'
    | '/$lang/instances/$instanceId/sharing'
    | '/$lang/instances/$instanceId/terminal'
    | '/$lang/instances/$instanceId/projects/$projectId'
    | '/$lang/instances/$instanceId/projects/$projectId/files'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_auth'
    | '/$lang/about'
    | '/$lang/admin'
    | '/$lang/cookie-policy'
    | '/$lang/device'
    | '/$lang/login'
    | '/$lang/signup'
    | '/$lang/'
    | '/$lang/_auth/dashboard'
    | '/$lang/_auth/instances'
    | '/$lang/_auth/settings'
    | '/$lang/admin/api-keys'
    | '/$lang/admin/assets'
    | '/$lang/admin/devices'
    | '/$lang/admin/enterprise'
    | '/$lang/admin/jobs'
    | '/$lang/admin/seed'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/admin/videos'
    | '/$lang/videos/$videoId'
    | '/$lang/admin/'
    | '/$lang/_auth/instances/$instanceId'
    | '/$lang/_auth/settings/privacy'
    | '/$lang/_auth/settings/security'
    | '/$lang/admin/assets/cleanup'
    | '/$lang/admin/videos/$videoId'
    | '/$lang/_auth/settings/'
    | '/$lang/admin/assets/'
    | '/$lang/admin/videos/'
    | '/$lang/_auth/instances/$instanceId/sharing'
    | '/$lang/_auth/instances/$instanceId/terminal'
    | '/$lang/_auth/instances/$instanceId/projects/$projectId'
    | '/$lang/_auth/instances/$instanceId/projects/$projectId/files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/signup': {
      id: '/$lang/signup'
      path: '/signup'
      fullPath: '/$lang/signup'
      preLoaderRoute: typeof LangSignupRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/device': {
      id: '/$lang/device'
      path: '/device'
      fullPath: '/$lang/device'
      preLoaderRoute: typeof LangDeviceRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/cookie-policy': {
      id: '/$lang/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/$lang/cookie-policy'
      preLoaderRoute: typeof LangCookiePolicyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_auth': {
      id: '/$lang/_auth'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/videos/$videoId': {
      id: '/$lang/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/$lang/videos/$videoId'
      preLoaderRoute: typeof LangVideosVideoIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/videos': {
      id: '/$lang/admin/videos'
      path: '/videos'
      fullPath: '/$lang/admin/videos'
      preLoaderRoute: typeof LangAdminVideosRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/users': {
      id: '/$lang/admin/users'
      path: '/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAdminUsersRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/settings': {
      id: '/$lang/admin/settings'
      path: '/settings'
      fullPath: '/$lang/admin/settings'
      preLoaderRoute: typeof LangAdminSettingsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/seed': {
      id: '/$lang/admin/seed'
      path: '/seed'
      fullPath: '/$lang/admin/seed'
      preLoaderRoute: typeof LangAdminSeedRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/jobs': {
      id: '/$lang/admin/jobs'
      path: '/jobs'
      fullPath: '/$lang/admin/jobs'
      preLoaderRoute: typeof LangAdminJobsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/enterprise': {
      id: '/$lang/admin/enterprise'
      path: '/enterprise'
      fullPath: '/$lang/admin/enterprise'
      preLoaderRoute: typeof LangAdminEnterpriseRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/devices': {
      id: '/$lang/admin/devices'
      path: '/devices'
      fullPath: '/$lang/admin/devices'
      preLoaderRoute: typeof LangAdminDevicesRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/assets': {
      id: '/$lang/admin/assets'
      path: '/assets'
      fullPath: '/$lang/admin/assets'
      preLoaderRoute: typeof LangAdminAssetsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/api-keys': {
      id: '/$lang/admin/api-keys'
      path: '/api-keys'
      fullPath: '/$lang/admin/api-keys'
      preLoaderRoute: typeof LangAdminApiKeysRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/_auth/settings': {
      id: '/$lang/_auth/settings'
      path: '/settings'
      fullPath: '/$lang/settings'
      preLoaderRoute: typeof LangAuthSettingsRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/_auth/instances': {
      id: '/$lang/_auth/instances'
      path: '/instances'
      fullPath: '/$lang/instances'
      preLoaderRoute: typeof LangAuthInstancesRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/_auth/dashboard': {
      id: '/$lang/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangAuthDashboardRouteImport
      parentRoute: typeof LangAuthRoute
    }
    '/$lang/admin/videos/': {
      id: '/$lang/admin/videos/'
      path: '/'
      fullPath: '/$lang/admin/videos/'
      preLoaderRoute: typeof LangAdminVideosIndexRouteImport
      parentRoute: typeof LangAdminVideosRoute
    }
    '/$lang/admin/assets/': {
      id: '/$lang/admin/assets/'
      path: '/'
      fullPath: '/$lang/admin/assets/'
      preLoaderRoute: typeof LangAdminAssetsIndexRouteImport
      parentRoute: typeof LangAdminAssetsRoute
    }
    '/$lang/_auth/settings/': {
      id: '/$lang/_auth/settings/'
      path: '/'
      fullPath: '/$lang/settings/'
      preLoaderRoute: typeof LangAuthSettingsIndexRouteImport
      parentRoute: typeof LangAuthSettingsRoute
    }
    '/$lang/admin/videos/$videoId': {
      id: '/$lang/admin/videos/$videoId'
      path: '/$videoId'
      fullPath: '/$lang/admin/videos/$videoId'
      preLoaderRoute: typeof LangAdminVideosVideoIdRouteImport
      parentRoute: typeof LangAdminVideosRoute
    }
    '/$lang/admin/assets/cleanup': {
      id: '/$lang/admin/assets/cleanup'
      path: '/cleanup'
      fullPath: '/$lang/admin/assets/cleanup'
      preLoaderRoute: typeof LangAdminAssetsCleanupRouteImport
      parentRoute: typeof LangAdminAssetsRoute
    }
    '/$lang/_auth/settings/security': {
      id: '/$lang/_auth/settings/security'
      path: '/security'
      fullPath: '/$lang/settings/security'
      preLoaderRoute: typeof LangAuthSettingsSecurityRouteImport
      parentRoute: typeof LangAuthSettingsRoute
    }
    '/$lang/_auth/settings/privacy': {
      id: '/$lang/_auth/settings/privacy'
      path: '/privacy'
      fullPath: '/$lang/settings/privacy'
      preLoaderRoute: typeof LangAuthSettingsPrivacyRouteImport
      parentRoute: typeof LangAuthSettingsRoute
    }
    '/$lang/_auth/instances/$instanceId': {
      id: '/$lang/_auth/instances/$instanceId'
      path: '/$instanceId'
      fullPath: '/$lang/instances/$instanceId'
      preLoaderRoute: typeof LangAuthInstancesInstanceIdRouteImport
      parentRoute: typeof LangAuthInstancesRoute
    }
    '/$lang/_auth/instances/$instanceId/terminal': {
      id: '/$lang/_auth/instances/$instanceId/terminal'
      path: '/terminal'
      fullPath: '/$lang/instances/$instanceId/terminal'
      preLoaderRoute: typeof LangAuthInstancesInstanceIdTerminalRouteImport
      parentRoute: typeof LangAuthInstancesInstanceIdRoute
    }
    '/$lang/_auth/instances/$instanceId/sharing': {
      id: '/$lang/_auth/instances/$instanceId/sharing'
      path: '/sharing'
      fullPath: '/$lang/instances/$instanceId/sharing'
      preLoaderRoute: typeof LangAuthInstancesInstanceIdSharingRouteImport
      parentRoute: typeof LangAuthInstancesInstanceIdRoute
    }
    '/$lang/_auth/instances/$instanceId/projects/$projectId': {
      id: '/$lang/_auth/instances/$instanceId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$lang/instances/$instanceId/projects/$projectId'
      preLoaderRoute: typeof LangAuthInstancesInstanceIdProjectsProjectIdRouteImport
      parentRoute: typeof LangAuthInstancesInstanceIdRoute
    }
    '/$lang/_auth/instances/$instanceId/projects/$projectId/files': {
      id: '/$lang/_auth/instances/$instanceId/projects/$projectId/files'
      path: '/files'
      fullPath: '/$lang/instances/$instanceId/projects/$projectId/files'
      preLoaderRoute: typeof LangAuthInstancesInstanceIdProjectsProjectIdFilesRouteImport
      parentRoute: typeof LangAuthInstancesInstanceIdProjectsProjectIdRoute
    }
  }
}

interface LangAuthInstancesInstanceIdProjectsProjectIdRouteChildren {
  LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute: typeof LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute
}

const LangAuthInstancesInstanceIdProjectsProjectIdRouteChildren: LangAuthInstancesInstanceIdProjectsProjectIdRouteChildren =
  {
    LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute:
      LangAuthInstancesInstanceIdProjectsProjectIdFilesRoute,
  }

const LangAuthInstancesInstanceIdProjectsProjectIdRouteWithChildren =
  LangAuthInstancesInstanceIdProjectsProjectIdRoute._addFileChildren(
    LangAuthInstancesInstanceIdProjectsProjectIdRouteChildren,
  )

interface LangAuthInstancesInstanceIdRouteChildren {
  LangAuthInstancesInstanceIdSharingRoute: typeof LangAuthInstancesInstanceIdSharingRoute
  LangAuthInstancesInstanceIdTerminalRoute: typeof LangAuthInstancesInstanceIdTerminalRoute
  LangAuthInstancesInstanceIdProjectsProjectIdRoute: typeof LangAuthInstancesInstanceIdProjectsProjectIdRouteWithChildren
}

const LangAuthInstancesInstanceIdRouteChildren: LangAuthInstancesInstanceIdRouteChildren =
  {
    LangAuthInstancesInstanceIdSharingRoute:
      LangAuthInstancesInstanceIdSharingRoute,
    LangAuthInstancesInstanceIdTerminalRoute:
      LangAuthInstancesInstanceIdTerminalRoute,
    LangAuthInstancesInstanceIdProjectsProjectIdRoute:
      LangAuthInstancesInstanceIdProjectsProjectIdRouteWithChildren,
  }

const LangAuthInstancesInstanceIdRouteWithChildren =
  LangAuthInstancesInstanceIdRoute._addFileChildren(
    LangAuthInstancesInstanceIdRouteChildren,
  )

interface LangAuthInstancesRouteChildren {
  LangAuthInstancesInstanceIdRoute: typeof LangAuthInstancesInstanceIdRouteWithChildren
}

const LangAuthInstancesRouteChildren: LangAuthInstancesRouteChildren = {
  LangAuthInstancesInstanceIdRoute:
    LangAuthInstancesInstanceIdRouteWithChildren,
}

const LangAuthInstancesRouteWithChildren =
  LangAuthInstancesRoute._addFileChildren(LangAuthInstancesRouteChildren)

interface LangAuthSettingsRouteChildren {
  LangAuthSettingsPrivacyRoute: typeof LangAuthSettingsPrivacyRoute
  LangAuthSettingsSecurityRoute: typeof LangAuthSettingsSecurityRoute
  LangAuthSettingsIndexRoute: typeof LangAuthSettingsIndexRoute
}

const LangAuthSettingsRouteChildren: LangAuthSettingsRouteChildren = {
  LangAuthSettingsPrivacyRoute: LangAuthSettingsPrivacyRoute,
  LangAuthSettingsSecurityRoute: LangAuthSettingsSecurityRoute,
  LangAuthSettingsIndexRoute: LangAuthSettingsIndexRoute,
}

const LangAuthSettingsRouteWithChildren =
  LangAuthSettingsRoute._addFileChildren(LangAuthSettingsRouteChildren)

interface LangAuthRouteChildren {
  LangAuthDashboardRoute: typeof LangAuthDashboardRoute
  LangAuthInstancesRoute: typeof LangAuthInstancesRouteWithChildren
  LangAuthSettingsRoute: typeof LangAuthSettingsRouteWithChildren
}

const LangAuthRouteChildren: LangAuthRouteChildren = {
  LangAuthDashboardRoute: LangAuthDashboardRoute,
  LangAuthInstancesRoute: LangAuthInstancesRouteWithChildren,
  LangAuthSettingsRoute: LangAuthSettingsRouteWithChildren,
}

const LangAuthRouteWithChildren = LangAuthRoute._addFileChildren(
  LangAuthRouteChildren,
)

interface LangAdminAssetsRouteChildren {
  LangAdminAssetsCleanupRoute: typeof LangAdminAssetsCleanupRoute
  LangAdminAssetsIndexRoute: typeof LangAdminAssetsIndexRoute
}

const LangAdminAssetsRouteChildren: LangAdminAssetsRouteChildren = {
  LangAdminAssetsCleanupRoute: LangAdminAssetsCleanupRoute,
  LangAdminAssetsIndexRoute: LangAdminAssetsIndexRoute,
}

const LangAdminAssetsRouteWithChildren = LangAdminAssetsRoute._addFileChildren(
  LangAdminAssetsRouteChildren,
)

interface LangAdminVideosRouteChildren {
  LangAdminVideosVideoIdRoute: typeof LangAdminVideosVideoIdRoute
  LangAdminVideosIndexRoute: typeof LangAdminVideosIndexRoute
}

const LangAdminVideosRouteChildren: LangAdminVideosRouteChildren = {
  LangAdminVideosVideoIdRoute: LangAdminVideosVideoIdRoute,
  LangAdminVideosIndexRoute: LangAdminVideosIndexRoute,
}

const LangAdminVideosRouteWithChildren = LangAdminVideosRoute._addFileChildren(
  LangAdminVideosRouteChildren,
)

interface LangAdminRouteChildren {
  LangAdminApiKeysRoute: typeof LangAdminApiKeysRoute
  LangAdminAssetsRoute: typeof LangAdminAssetsRouteWithChildren
  LangAdminDevicesRoute: typeof LangAdminDevicesRoute
  LangAdminEnterpriseRoute: typeof LangAdminEnterpriseRoute
  LangAdminJobsRoute: typeof LangAdminJobsRoute
  LangAdminSeedRoute: typeof LangAdminSeedRoute
  LangAdminSettingsRoute: typeof LangAdminSettingsRoute
  LangAdminUsersRoute: typeof LangAdminUsersRoute
  LangAdminVideosRoute: typeof LangAdminVideosRouteWithChildren
  LangAdminIndexRoute: typeof LangAdminIndexRoute
}

const LangAdminRouteChildren: LangAdminRouteChildren = {
  LangAdminApiKeysRoute: LangAdminApiKeysRoute,
  LangAdminAssetsRoute: LangAdminAssetsRouteWithChildren,
  LangAdminDevicesRoute: LangAdminDevicesRoute,
  LangAdminEnterpriseRoute: LangAdminEnterpriseRoute,
  LangAdminJobsRoute: LangAdminJobsRoute,
  LangAdminSeedRoute: LangAdminSeedRoute,
  LangAdminSettingsRoute: LangAdminSettingsRoute,
  LangAdminUsersRoute: LangAdminUsersRoute,
  LangAdminVideosRoute: LangAdminVideosRouteWithChildren,
  LangAdminIndexRoute: LangAdminIndexRoute,
}

const LangAdminRouteWithChildren = LangAdminRoute._addFileChildren(
  LangAdminRouteChildren,
)

interface LangRouteChildren {
  LangAuthRoute: typeof LangAuthRouteWithChildren
  LangAboutRoute: typeof LangAboutRoute
  LangAdminRoute: typeof LangAdminRouteWithChildren
  LangCookiePolicyRoute: typeof LangCookiePolicyRoute
  LangDeviceRoute: typeof LangDeviceRoute
  LangLoginRoute: typeof LangLoginRoute
  LangSignupRoute: typeof LangSignupRoute
  LangIndexRoute: typeof LangIndexRoute
  LangVideosVideoIdRoute: typeof LangVideosVideoIdRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAuthRoute: LangAuthRouteWithChildren,
  LangAboutRoute: LangAboutRoute,
  LangAdminRoute: LangAdminRouteWithChildren,
  LangCookiePolicyRoute: LangCookiePolicyRoute,
  LangDeviceRoute: LangDeviceRoute,
  LangLoginRoute: LangLoginRoute,
  LangSignupRoute: LangSignupRoute,
  LangIndexRoute: LangIndexRoute,
  LangVideosVideoIdRoute: LangVideosVideoIdRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
