#!/usr/bin/env python3
"""Generate checked runtime prerequisite documentation from catalog IDs.

This generator is deliberately offline and side-effect free outside the two
repository-owned outputs. It validates that the media IDs are registered in
the Rust catalog before rendering them, preventing prose-only dependencies.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CATALOG = ROOT / "crates/cockpit-core/src/external_runtime/adapters.rs"
DOC = ROOT / "apps/docs/src/content/docs/reference/runtime-prerequisites.md"
WARNING = ROOT / "apps/cli/generated/runtime-prerequisites.txt"
IDS = ("ID_MEDIA_FFMPEG", "ID_MEDIA_FFPROBE", "ID_BUBBLEWRAP")

DOCUMENT_TEMPLATE = """---
title: Runtime prerequisites
description: Optional host tools used by Cockpit features
---

Cockpit does not download, bundle, or install external runtimes. Dependency
checks are read-only. Open **Settings → Dependencies** or run
`cockpit doctor --dependencies-json` to see current health and catalog guidance.

## Media support

| Selected input | Decoder | Catalog health IDs | Behavior when unavailable |
| --- | --- | --- | --- |
| PNG, JPEG, GIF, WebP | Native | None | Decodes natively |
| WAV, MP3, M4A, FLAC, Ogg | FFmpeg + FFprobe | `{ffmpeg_id}`, `{ffprobe_id}` | Selection fails closed |
| MP4, WebM, MOV | FFmpeg + FFprobe | `{ffmpeg_id}`, `{ffprobe_id}` | Selection fails closed |

Install a compatible FFmpeg/FFprobe pair using the official instructions at
https://ffmpeg.org/download.html. Verify with `ffmpeg -version` and
`ffprobe -version`; refresh the health snapshot in Settings or rerun `cockpit
doctor --dependencies-json`. Uninstall using the same system package source.
Unknown platforms receive only the official link and verification commands.

## Linux shell sandbox

Bubblewrap (`{bubblewrap_id}`) strengthens the host shell sandbox on Linux.
Its absence produces a warning but never makes installation fail and never
runs a package manager. Follow https://github.com/containers/bubblewrap/blob/main/README.md,
verify with `bwrap --version`, refresh dependency health, and uninstall using
the system package source if it is no longer wanted.

## Cockpit installation assets

Release archives and SHA-256 checksums, plus the POSIX and PowerShell
installers, are generated by cargo-dist. They install the single `cockpit`
executable into Cargo's bin directory (`$CARGO_HOME/bin`, defaulting to
`$HOME/.cargo/bin` on POSIX and `%USERPROFILE%\\.cargo\\bin` on Windows).
Installers do not edit shell startup files. Add that directory to `PATH` when
prompted. Shell completions and man pages are explicit archive assets; see the
CLI README for installation and removal steps.
"""

WARNING_TEXT = """Cockpit external runtime notice

Cockpit does not install host dependencies. Missing Bubblewrap is a warning and
does not fail installation. Selected audio/video inputs require a compatible
FFmpeg and FFprobe pair; images decode natively. Diagnose with:
  cockpit doctor --dependencies-json
Documentation: https://docs.flycockpit.com/reference/runtime-prerequisites/
"""


def catalog_values() -> dict[str, str]:
    source = CATALOG.read_text()
    missing = [item for item in IDS[:2] if source.count(item) < 3]
    safety = (CATALOG.parent / "safety_adapters.rs").read_text()
    if IDS[2] not in safety:
        missing.append(IDS[2])
    if missing:
        raise SystemExit(f"runtime catalog is missing registered IDs: {', '.join(missing)}")
    values: dict[str, str] = {}
    for name, text in ((IDS[0], source), (IDS[1], source), (IDS[2], safety)):
        match = re.search(rf'pub const {name}: &str = "([^"]+)";', text)
        if not match:
            raise SystemExit(f"could not read catalog value for {name}")
        values[name] = match.group(1)
    return values


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = catalog_values()
    document = DOCUMENT_TEMPLATE.format(
        ffmpeg_id=values[IDS[0]],
        ffprobe_id=values[IDS[1]],
        bubblewrap_id=values[IDS[2]],
    )
    if args.check:
        if not DOC.exists() or DOC.read_text() != document:
            raise SystemExit(f"generated documentation drift: {DOC.relative_to(ROOT)}")
        if not WARNING.exists() or WARNING.read_text() != WARNING_TEXT:
            raise SystemExit(f"generated warning drift: {WARNING.relative_to(ROOT)}")
        return 0
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(document)
    WARNING.parent.mkdir(parents=True, exist_ok=True)
    WARNING.write_text(WARNING_TEXT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
