-- Utility-call flag (prompt `export-debug-utility-version-config.md`): mark an
-- inference call as made by the utility model / background machinery
-- (auto-titling, auto-router, prompt-injection guard, next-message prediction,
-- the `/compact` handoff brief, …) rather than a foreground user turn.
--
-- Persisted at the time the call is recorded so the `/export debug` bundle can
-- read it reliably and split utility calls into a sibling
-- `inference_requests_utility/` folder without inferring anything at export
-- time. Defaults to false (0); pre-migration calls therefore stay non-utility
-- (no backfill).
ALTER TABLE inference_calls ADD COLUMN is_utility INTEGER NOT NULL DEFAULT 0;
